/*
 * AUTO-GENERATED COMPATIBILITY STUB.
 *
 * The recovered source tree imports this module, but the original file is
 * absent from this checkout. This stub only exists so local tooling can
 * resolve modules; it is not a replacement for the original implementation.
 */

type StubCallable = ((...args: unknown[]) => unknown) & Record<PropertyKey, unknown>

const createStub = (label: string): StubCallable => {
  const target = function compatibilityStub() {
    throw new Error(`Missing original implementation for src/components/agents/SnapshotUpdateDialog.ts (${label})`)
  } as StubCallable
  return new Proxy(target, {
    get(current, prop) {
      if (prop === 'then') return undefined
      if (prop === Symbol.toStringTag) return 'CompatibilityStub'
      if (prop in current) return current[prop]
      return createStub(`${label}.${String(prop)}`)
    },
    apply() {
      throw new Error(`Missing original implementation for src/components/agents/SnapshotUpdateDialog.ts (${label})`)
    },
    construct() {
      throw new Error(`Missing original implementation for src/components/agents/SnapshotUpdateDialog.ts (${label})`)
    },
  })
}

const stub = createStub("src/components/agents/SnapshotUpdateDialog.ts")

export type BigQuery = any
export type Edit = any
export type FilesApiConfig = any
export type Gmail = any
export type InvalidArgumentError = any
export type LSP = any
export type McpServerConfig = any
export type TeleportOperationError = any
export type act = any
export type activeAgents = any
export type addDir = any
export type addDirs = any
export type agentName = any
export type allAgents = any
export type allowDangerouslySkipPermissions = any
export type allowedTools = any
export type are_unsandboxed_commands_allowed = any
export type attribution = any
export type auth = any
export type authToken = any
export type auto_updater_disabled = any
export type b = any
export type baseToolsCli = any
export type betas = any
export type but = any
export type ccUrl = any
export type color = any
export type commands = any
export type config = any
export type countFiles = any
export type cwd = any
export type dangerousPermissions = any
export type dangerouslySkipPermissions = any
export type debugToStderr = any
export type dedupAstroAiMcpServers = any
export type dev_count = any
export type dev_plugins = any
export type disallowedTools = any
export type disallowedToolsCli = any
export type discover = any
export type doesEnterpriseMcpConfigExist = any
export type downloadSessionFiles = any
export type durationMs = any
export type enableAstroInChrome = any
export type exitWithMessage = any
export type expandVars = any
export type extraCliArgs = any
export type fallbackModel = any
export type filePath = any
export type filterMcpServersByPolicy = any
export type flag = any
export type getAgentDefinitionsWithOverrides = any
export type getAutoModeEnabledStateIfCached = any
export type getBranch = any
export type getAstroCodeMcpConfigs = any
export type getDefaultAppState = any
export type getErrnoCode = any
export type getGlobalConfig = any
export type getInitialAdvisorSetting = any
export type getInitialMainLoopModel = any
export type getIsGit = any
export type getIsNonInteractiveSession = any
export type getManagedSettingsKeysForLogging = any
export type getMcpServerSignature = any
export type getRemoteControlAtStartup = any
export type getRenderContext = any
export type getSdkBetas = any
export type getSessionId = any
export type getSessionIdFromLog = any
export type getSettingsForSource = any
export type getUserContext = any
export type getUserMsgOptIn = any
export type getUserSpecifiedModelSetting = any
export type gh_auth_status = any
export type has_required_fields = any
export type high = any
export type ide = any
export type includeHookEvents = any
export type initialPermissionModeFromCLI = any
export type initializeGrowthBook = any
export type initializeToolPermissionContext = any
export type inputFormat = any
export type isAdvisorEnabled = any
export type isAutoUpdaterDisabled = any
export type isBareMode = any
export type isBuiltInAgent = any
export type isAstroAISubscriber = any
export type isCustomAgent = any
export type isDefaultPermissionModeAuto = any
export type isENOENT = any
export type isEnvTruthy = any
export type isFastModeEnabled = any
export type isTmuxAvailable = any
export type isValidAdvisorModel = any
export type is_auto_bash_allowed_if_sandbox_enabled = any
export type keys = any
export type launchAssistantSessionChooser = any
export type launchInvalidSettingsDialog = any
export type launchResumeChooser = any
export type launchSnapshotUpdateDialog = any
export type launchTeleportRepoMismatchDialog = any
export type loadPolicyLimits = any
export type loadTranscriptFromFile = any
export type local = any
export type managedNames = any
export type marketplace = any
export type mcp = any
export type mcpConfig = any
export type medium = any
export type migrationVersion = any
export type name = any
export type normalizeModelStringForAPI = any
export type notification = any
export type oauthToken = any
export type onCancel = any
export type opts = any
export type parentSessionId = any
export type parseMcpConfig = any
export type parseToolListFromCLI = any
export type permissionMode = any
export type planModeRequired = any
export type plugin = any
export type plugins = any
export type prefers_reduced_motion = any
export type prefetchAwsCredentialsAndBedRockInfoIfSafe = any
export type prefetchFastModeStatus = any
export type prefetchGcpCredentialsIfSafe = any
export type prev = any
export type processMessagesForTeleportResume = any
export type profileCheckpoint = any
export type project = any
export type props = any
export type refreshPolicyLimits = any
export type registerSession = any
export type removeDangerousPermissions = any
export type renderAndRun = any
export type sandbox_enabled = any
export type saveAgentSetting = any
export type saveMode = any
export type scope = any
export type searchSessionsByCustomTitle = any
export type sessionId = any
export type setAdditionalDirectoriesForAstroMd = any
export type setAllowedChannels = any
export type setAllowedSettingSources = any
export type setChromeFlagOverride = any
export type setClientType = any
export type setCwdState = any
export type setDirectConnectServerUrl = any
export type setFlagSettingsPath = any
export type setInitialMainLoopModel = any
export type setInlinePlugins = any
export type setIsInteractive = any
export type setIsRemoteMode = any
export type setKairosActive = any
export type setMainLoopModelOverride = any
export type setMainThreadAgentType = any
export type setOriginalCwd = any
export type setQuestionPreviewFormat = any
export type setSdkBetas = any
export type setSessionBypassPermissionsMode = any
export type setSessionPersistenceDisabled = any
export type setSessionSource = any
export type setUserMsgOptIn = any
export type shouldAutoEnableAstroInChrome = any
export type skills = any
export type snapshotTimestamp = any
export type sortOptions = any
export type source = any
export type stripDangerousPermissionsForAutoMode = any
export type systemPrompt = any
export type teamName = any
export type teleportToRemoteWithErrorHandling = any
export type the = any
export type tips = any
export type tmuxEnabled = any
export type tools = any
export type trimmedSettings = any
export type validateGitState = any
export type value = any
export type worktreeCount = any
export type worktreeEnabled = any
export type worktreeName = any
export type worktreePRNumber = any
export type worktree_count = any

export const BigQuery: any = stub
export const Edit: any = stub
export const FilesApiConfig: any = stub
export const Gmail: any = stub
export const InvalidArgumentError: any = stub
export const LSP: any = stub
export const McpServerConfig: any = stub
export const TeleportOperationError: any = stub
export const act: any = stub
export const activeAgents: any = stub
export const addDir: any = stub
export const addDirs: any = stub
export const agentName: any = stub
export const allAgents: any = stub
export const allowDangerouslySkipPermissions: any = stub
export const allowedTools: any = stub
export const are_unsandboxed_commands_allowed: any = stub
export const attribution: any = stub
export const auth: any = stub
export const authToken: any = stub
export const auto_updater_disabled: any = stub
export const b: any = stub
export const baseToolsCli: any = stub
export const betas: any = stub
export const but: any = stub
export const ccUrl: any = stub
export const color: any = stub
export const commands: any = stub
export const config: any = stub
export const countFiles: any = stub
export const cwd: any = stub
export const dangerousPermissions: any = stub
export const dangerouslySkipPermissions: any = stub
export const debugToStderr: any = stub
export const dedupAstroAiMcpServers: any = stub
export const dev_count: any = stub
export const dev_plugins: any = stub
export const disallowedTools: any = stub
export const disallowedToolsCli: any = stub
export const discover: any = stub
export const doesEnterpriseMcpConfigExist: any = stub
export const downloadSessionFiles: any = stub
export const durationMs: any = stub
export const enableAstroInChrome: any = stub
export const exitWithMessage: any = stub
export const expandVars: any = stub
export const extraCliArgs: any = stub
export const fallbackModel: any = stub
export const filePath: any = stub
export const filterMcpServersByPolicy: any = stub
export const flag: any = stub
export const getAgentDefinitionsWithOverrides: any = stub
export const getAutoModeEnabledStateIfCached: any = stub
export const getBranch: any = stub
export const getAstroCodeMcpConfigs: any = stub
export const getDefaultAppState: any = stub
export const getErrnoCode: any = stub
export const getGlobalConfig: any = stub
export const getInitialAdvisorSetting: any = stub
export const getInitialMainLoopModel: any = stub
export const getIsGit: any = stub
export const getIsNonInteractiveSession: any = stub
export const getManagedSettingsKeysForLogging: any = stub
export const getMcpServerSignature: any = stub
export const getRemoteControlAtStartup: any = stub
export const getRenderContext: any = stub
export const getSdkBetas: any = stub
export const getSessionId: any = stub
export const getSessionIdFromLog: any = stub
export const getSettingsForSource: any = stub
export const getUserContext: any = stub
export const getUserMsgOptIn: any = stub
export const getUserSpecifiedModelSetting: any = stub
export const gh_auth_status: any = stub
export const has_required_fields: any = stub
export const high: any = stub
export const ide: any = stub
export const includeHookEvents: any = stub
export const initialPermissionModeFromCLI: any = stub
export const initializeGrowthBook: any = stub
export const initializeToolPermissionContext: any = stub
export const inputFormat: any = stub
export const isAdvisorEnabled: any = stub
export const isAutoUpdaterDisabled: any = stub
export const isBareMode: any = stub
export const isBuiltInAgent: any = stub
export const isAstroAISubscriber: any = stub
export const isCustomAgent: any = stub
export const isDefaultPermissionModeAuto: any = stub
export const isENOENT: any = stub
export const isEnvTruthy: any = stub
export const isFastModeEnabled: any = stub
export const isTmuxAvailable: any = stub
export const isValidAdvisorModel: any = stub
export const is_auto_bash_allowed_if_sandbox_enabled: any = stub
export const keys: any = stub
export const launchAssistantSessionChooser: any = stub
export const launchInvalidSettingsDialog: any = stub
export const launchResumeChooser: any = stub
export const launchSnapshotUpdateDialog: any = stub
export const launchTeleportRepoMismatchDialog: any = stub
export const loadPolicyLimits: any = stub
export const loadTranscriptFromFile: any = stub
export const local: any = stub
export const managedNames: any = stub
export const marketplace: any = stub
export const mcp: any = stub
export const mcpConfig: any = stub
export const medium: any = stub
export const migrationVersion: any = stub
export const name: any = stub
export const normalizeModelStringForAPI: any = stub
export const notification: any = stub
export const oauthToken: any = stub
export const onCancel: any = stub
export const opts: any = stub
export const parentSessionId: any = stub
export const parseMcpConfig: any = stub
export const parseToolListFromCLI: any = stub
export const permissionMode: any = stub
export const planModeRequired: any = stub
export const plugin: any = stub
export const plugins: any = stub
export const prefers_reduced_motion: any = stub
export const prefetchAwsCredentialsAndBedRockInfoIfSafe: any = stub
export const prefetchFastModeStatus: any = stub
export const prefetchGcpCredentialsIfSafe: any = stub
export const prev: any = stub
export const processMessagesForTeleportResume: any = stub
export const profileCheckpoint: any = stub
export const project: any = stub
export const props: any = stub
export const refreshPolicyLimits: any = stub
export const registerSession: any = stub
export const removeDangerousPermissions: any = stub
export const renderAndRun: any = stub
export const sandbox_enabled: any = stub
export const saveAgentSetting: any = stub
export const saveMode: any = stub
export const scope: any = stub
export const searchSessionsByCustomTitle: any = stub
export const sessionId: any = stub
export const setAdditionalDirectoriesForAstroMd: any = stub
export const setAllowedChannels: any = stub
export const setAllowedSettingSources: any = stub
export const setChromeFlagOverride: any = stub
export const setClientType: any = stub
export const setCwdState: any = stub
export const setDirectConnectServerUrl: any = stub
export const setFlagSettingsPath: any = stub
export const setInitialMainLoopModel: any = stub
export const setInlinePlugins: any = stub
export const setIsInteractive: any = stub
export const setIsRemoteMode: any = stub
export const setKairosActive: any = stub
export const setMainLoopModelOverride: any = stub
export const setMainThreadAgentType: any = stub
export const setOriginalCwd: any = stub
export const setQuestionPreviewFormat: any = stub
export const setSdkBetas: any = stub
export const setSessionBypassPermissionsMode: any = stub
export const setSessionPersistenceDisabled: any = stub
export const setSessionSource: any = stub
export const setUserMsgOptIn: any = stub
export const shouldAutoEnableAstroInChrome: any = stub
export const skills: any = stub
export const snapshotTimestamp: any = stub
export const sortOptions: any = stub
export const source: any = stub
export const stripDangerousPermissionsForAutoMode: any = stub
export const systemPrompt: any = stub
export const teamName: any = stub
export const teleportToRemoteWithErrorHandling: any = stub
export const the: any = stub
export const tips: any = stub
export const tmuxEnabled: any = stub
export const tools: any = stub
export const trimmedSettings: any = stub
export const validateGitState: any = stub
export const value: any = stub
export const worktreeCount: any = stub
export const worktreeEnabled: any = stub
export const worktreeName: any = stub
export const worktreePRNumber: any = stub
export const worktree_count: any = stub

export default stub
