/*
 * AUTO-GENERATED COMPATIBILITY STUB.
 *
 * The recovered source tree imports this module, but the original file is
 * absent from this checkout. This stub only exists so local tooling can
 * resolve modules; it is not a replacement for the original implementation.
 */

type StubCallable = ((...args: unknown[]) => unknown) & Record<PropertyKey, unknown>

const createStub = (label: string): StubCallable => {
  const target = function compatibilityStub() {
    throw new Error(`Missing original implementation for src/assistant/sessionDiscovery.ts (${label})`)
  } as StubCallable
  return new Proxy(target, {
    get(current, prop) {
      if (prop === 'then') return undefined
      if (prop === Symbol.toStringTag) return 'CompatibilityStub'
      if (prop in current) return current[prop]
      return createStub(`${label}.${String(prop)}`)
    },
    apply() {
      throw new Error(`Missing original implementation for src/assistant/sessionDiscovery.ts (${label})`)
    },
    construct() {
      throw new Error(`Missing original implementation for src/assistant/sessionDiscovery.ts (${label})`)
    },
  })
}

const stub = createStub("src/assistant/sessionDiscovery.ts")

export type AssistantSession = any
export type BigQuery = any
export type ASTRO_AI_MCP_TIMEOUT_MS = any
export type Edit = any
export type FilesApiConfig = any
export type Gmail = any
export type InvalidArgumentError = any
export type LSP = any
export type McpServerConfig = any
export type TeleportOperationError = any
export type acceptedAt = any
export type act = any
export type activeAgents = any
export type activeOverlays = any
export type addDir = any
export type addDirs = any
export type agent = any
export type agentDefinitions = any
export type agentName = any
export type agentNameRegistry = any
export type allAgents = any
export type allowDangerouslySkipPermissions = any
export type allowDangerouslySkipPermissionsPassed = any
export type allowedTools = any
export type appendSystemPrompt = any
export type appendSystemPromptFlag = any
export type are_unsandboxed_commands_allowed = any
export type assistantActivationPath = any
export type attribution = any
export type auth = any
export type authToken = any
export type authVersion = any
export type autoConnectIdeFlag = any
export type auto_updater_disabled = any
export type b = any
export type baseToolsCli = any
export type betas = any
export type budgetTokens = any
export type but = any
export type ccUrl = any
export type cliAgents = any
export type clients = any
export type color = any
export type commands = any
export type commandsHeadless = any
export type config = any
export type coordinatorTaskIndex = any
export type countFiles = any
export type createLocalSSHSession = any
export type currentCwd = any
export type cwd = any
export type dangerousPermissions = any
export type dangerouslySkipPermissions = any
export type dangerouslySkipPermissionsPassed = any
export type debug = any
export type debugToStderr = any
export type dedupAstroAiMcpServers = any
export type dev_count = any
export type dev_plugins = any
export type directConnectConfig = any
export type disableSlashCommands = any
export type disabled = any
export type disallowedTools = any
export type disallowedToolsCli = any
export type discover = any
export type doesEnterpriseMcpConfigExist = any
export type downloadSessionFiles = any
export type durationMs = any
export type dynamicMcpConfig = any
export type effortValue = any
export type elicitation = any
export type enableAuthStatus = any
export type enableAstroInChrome = any
export type env_var = any
export type errors = any
export type exitWithMessage = any
export type expandVars = any
export type expandedView = any
export type extraCliArgs = any
export type fallbackModel = any
export type fastMode = any
export type fileHistory = any
export type filePath = any
export type filterMcpServersByPolicy = any
export type flag = any
export type footerSelection = any
export type forkSession = any
export type generationRequestId = any
export type getAgentDefinitionsWithOverrides = any
export type getAutoModeEnabledStateIfCached = any
export type getBranch = any
export type getAstroCodeMcpConfigs = any
export type getDefaultAppState = any
export type getErrnoCode = any
export type getGlobalConfig = any
export type getInitialAdvisorSetting = any
export type getInitialMainLoopModel = any
export type getIsGit = any
export type getIsNonInteractiveSession = any
export type getManagedSettingsKeysForLogging = any
export type getMcpServerSignature = any
export type getRemoteControlAtStartup = any
export type getRenderContext = any
export type getSdkBetas = any
export type getSessionId = any
export type getSessionIdFromLog = any
export type getSettingsForSource = any
export type getUserContext = any
export type getUserMsgOptIn = any
export type getUserSpecifiedModelSetting = any
export type gh_auth_status = any
export type githubActionInputs = any
export type hand = any
export type hasStdin = any
export type has_required_fields = any
export type high = any
export type ide = any
export type inbox = any
export type includeAttribution = any
export type includeHookEvents = any
export type includePartialMessages = any
export type initialAgentColor = any
export type initialAgentName = any
export type initialContentReplacements = any
export type initialFileHistorySnapshots = any
export type initialMessage = any
export type initialMessages = any
export type initialPermissionModeFromCLI = any
export type initialState = any
export type initialTools = any
export type initializeGrowthBook = any
export type initializeToolPermissionContext = any
export type inputFormat = any
export type installationStatus = any
export type isAdvisorEnabled = any
export type isAutoUpdaterDisabled = any
export type isBareMode = any
export type isBriefOnly = any
export type isBuiltInAgent = any
export type isAstroAISubscriber = any
export type isCustomAgent = any
export type isDefaultPermissionModeAuto = any
export type isENOENT = any
export type isEnvTruthy = any
export type isFastModeEnabled = any
export type isTmuxAvailable = any
export type isValidAdvisorModel = any
export type is_auto_bash_allowed_if_sandbox_enabled = any
export type is_native_binary = any
export type jsonSchema = any
export type kairosEnabled = any
export type keys = any
export type label = any
export type launchAssistantSessionChooser = any
export type launchInvalidSettingsDialog = any
export type launchResumeChooser = any
export type launchSnapshotUpdateDialog = any
export type launchTeleportRepoMismatchDialog = any
export type loadPolicyLimits = any
export type loadTranscriptFromFile = any
export type local = any
export type localVersion = any
export type mainLoopModel = any
export type mainLoopModelForSession = any
export type mainThreadAgentDefinition = any
export type managedNames = any
export type marketplace = any
export type maxBudgetUsd = any
export type maxTurns = any
export type mcp = any
export type mcpClientCount = any
export type mcpClients = any
export type mcpConfig = any
export type medium = any
export type migrationVersion = any
export type mode = any
export type modeIsBypass = any
export type model = any
export type name = any
export type needsRefresh = any
export type normalizeModelStringForAPI = any
export type notification = any
export type notifications = any
export type numAllowedTools = any
export type numDisallowedTools = any
export type numStartups = any
export type oauthToken = any
export type onExit = any
export type opts = any
export type outputFormat = any
export type parentSessionId = any
export type parseMcpConfig = any
export type parseToolListFromCLI = any
export type passes = any
export type pendingSandboxRequest = any
export type pendingWorkerRequest = any
export type permissionMode = any
export type permissionPromptToolName = any
export type planModeRequired = any
export type plugin = any
export type pluginReconnectKey = any
export type plugins = any
export type prefers_reduced_motion = any
export type prefetchAwsCredentialsAndBedRockInfoIfSafe = any
export type prefetchFastModeStatus = any
export type prefetchGcpCredentialsIfSafe = any
export type prev = any
export type print = any
export type priority = any
export type processMessagesForTeleportResume = any
export type profileCheckpoint = any
export type project = any
export type promptId = any
export type promptSuggestion = any
export type promptSuggestionEnabled = any
export type pruneShellSnapshots = any
export type queue = any
export type refreshPolicyLimits = any
export type registerSession = any
export type remoteAgentTaskSuggestions = any
export type remoteBackgroundTaskCount = any
export type remoteConnectionStatus = any
export type remoteSessionUrl = any
export type removeDangerousPermissions = any
export type renderAndRun = any
export type replBridgeConnectUrl = any
export type replBridgeConnected = any
export type replBridgeEnabled = any
export type replBridgeEnvironmentId = any
export type replBridgeError = any
export type replBridgeExplicit = any
export type replBridgeInitialName = any
export type replBridgeOutboundOnly = any
export type replBridgeReconnecting = any
export type replBridgeSessionActive = any
export type replBridgeSessionId = any
export type replBridgeSessionUrl = any
export type replayUserMessages = any
export type resources = any
export type resume = any
export type resumeSessionAt = any
export type resume_duration_ms = any
export type rewindFiles = any
export type sandbox_enabled = any
export type saveAgentSetting = any
export type saveMode = any
export type scope = any
export type sdkMcpConfigs = any
export type sdkUrl = any
export type searchSessionsByCustomTitle = any
export type selectedIPAgentIndex = any
export type selectedIndex = any
export type sessionHooks = any
export type sessionId = any
export type setAdditionalDirectoriesForAstroMd = any
export type setAllowedChannels = any
export type setAllowedSettingSources = any
export type setChromeFlagOverride = any
export type setClientType = any
export type setCwdState = any
export type setDirectConnectServerUrl = any
export type setFlagSettingsPath = any
export type setInitialMainLoopModel = any
export type setInlinePlugins = any
export type setIsInteractive = any
export type setIsRemoteMode = any
export type setKairosActive = any
export type setMainLoopModelOverride = any
export type setMainThreadAgentType = any
export type setOriginalCwd = any
export type setQuestionPreviewFormat = any
export type setSdkBetas = any
export type setSessionBypassPermissionsMode = any
export type setSessionPersistenceDisabled = any
export type setSessionSource = any
export type setUserMsgOptIn = any
export type settings_file = any
export type setupTrigger = any
export type shouldAutoEnableAstroInChrome = any
export type showRemoteCallout = any
export type showTeammateMessagePreview = any
export type shownAt = any
export type skillImprovement = any
export type skills = any
export type skipWebFetchPreflight = any
export type snapshotSequence = any
export type snapshotTimestamp = any
export type sortOptions = any
export type source = any
export type speculation = any
export type speculationSessionTimeSavedMs = any
export type sshSession = any
export type startupPrefetchedAt = any
export type stats = any
export type statusLineText = any
export type strictMcpConfig = any
export type stripDangerousPermissionsForAutoMode = any
export type subscriptionType = any
export type systemPrompt = any
export type systemPromptFlag = any
export type taskBudget = any
export type taskListId = any
export type tasks = any
export type teamName = any
export type teleport = any
export type teleportToRemoteWithErrorHandling = any
export type text = any
export type the = any
export type thinkingConfig = any
export type thinkingEnabled = any
export type tips = any
export type tmuxEnabled = any
export type todos = any
export type toolPermissionContext = any
export type tools = any
export type trackedFiles = any
export type transcriptPath = any
export type trimmedSettings = any
export type type = any
export type userSpecifiedModel = any
export type validateGitState = any
export type value = any
export type verbose = any
export type viewSelectionMode = any
export type workerSandboxPermissions = any
export type workload = any
export type worktreeCount = any
export type worktreeEnabled = any
export type worktreeName = any
export type worktreePRNumber = any
export type worktree_count = any

export const BigQuery: any = stub
export const ASTRO_AI_MCP_TIMEOUT_MS: any = stub
export const Edit: any = stub
export const FilesApiConfig: any = stub
export const Gmail: any = stub
export const InvalidArgumentError: any = stub
export const LSP: any = stub
export const McpServerConfig: any = stub
export const TeleportOperationError: any = stub
export const acceptedAt: any = stub
export const act: any = stub
export const activeAgents: any = stub
export const activeOverlays: any = stub
export const addDir: any = stub
export const addDirs: any = stub
export const agent: any = stub
export const agentDefinitions: any = stub
export const agentName: any = stub
export const agentNameRegistry: any = stub
export const allAgents: any = stub
export const allowDangerouslySkipPermissions: any = stub
export const allowDangerouslySkipPermissionsPassed: any = stub
export const allowedTools: any = stub
export const appendSystemPrompt: any = stub
export const appendSystemPromptFlag: any = stub
export const are_unsandboxed_commands_allowed: any = stub
export const assistantActivationPath: any = stub
export const attribution: any = stub
export const auth: any = stub
export const authToken: any = stub
export const authVersion: any = stub
export const autoConnectIdeFlag: any = stub
export const auto_updater_disabled: any = stub
export const b: any = stub
export const baseToolsCli: any = stub
export const betas: any = stub
export const budgetTokens: any = stub
export const but: any = stub
export const ccUrl: any = stub
export const cliAgents: any = stub
export const clients: any = stub
export const color: any = stub
export const commands: any = stub
export const commandsHeadless: any = stub
export const config: any = stub
export const coordinatorTaskIndex: any = stub
export const countFiles: any = stub
export const createLocalSSHSession: any = stub
export const currentCwd: any = stub
export const cwd: any = stub
export const dangerousPermissions: any = stub
export const dangerouslySkipPermissions: any = stub
export const dangerouslySkipPermissionsPassed: any = stub
export const debug: any = stub
export const debugToStderr: any = stub
export const dedupAstroAiMcpServers: any = stub
export const dev_count: any = stub
export const dev_plugins: any = stub
export const directConnectConfig: any = stub
export const disableSlashCommands: any = stub
export const disabled: any = stub
export const disallowedTools: any = stub
export const disallowedToolsCli: any = stub
export const discover: any = stub
export const doesEnterpriseMcpConfigExist: any = stub
export const downloadSessionFiles: any = stub
export const durationMs: any = stub
export const dynamicMcpConfig: any = stub
export const effortValue: any = stub
export const elicitation: any = stub
export const enableAuthStatus: any = stub
export const enableAstroInChrome: any = stub
export const env_var: any = stub
export const errors: any = stub
export const exitWithMessage: any = stub
export const expandVars: any = stub
export const expandedView: any = stub
export const extraCliArgs: any = stub
export const fallbackModel: any = stub
export const fastMode: any = stub
export const fileHistory: any = stub
export const filePath: any = stub
export const filterMcpServersByPolicy: any = stub
export const flag: any = stub
export const footerSelection: any = stub
export const forkSession: any = stub
export const generationRequestId: any = stub
export const getAgentDefinitionsWithOverrides: any = stub
export const getAutoModeEnabledStateIfCached: any = stub
export const getBranch: any = stub
export const getAstroCodeMcpConfigs: any = stub
export const getDefaultAppState: any = stub
export const getErrnoCode: any = stub
export const getGlobalConfig: any = stub
export const getInitialAdvisorSetting: any = stub
export const getInitialMainLoopModel: any = stub
export const getIsGit: any = stub
export const getIsNonInteractiveSession: any = stub
export const getManagedSettingsKeysForLogging: any = stub
export const getMcpServerSignature: any = stub
export const getRemoteControlAtStartup: any = stub
export const getRenderContext: any = stub
export const getSdkBetas: any = stub
export const getSessionId: any = stub
export const getSessionIdFromLog: any = stub
export const getSettingsForSource: any = stub
export const getUserContext: any = stub
export const getUserMsgOptIn: any = stub
export const getUserSpecifiedModelSetting: any = stub
export const gh_auth_status: any = stub
export const githubActionInputs: any = stub
export const hand: any = stub
export const hasStdin: any = stub
export const has_required_fields: any = stub
export const high: any = stub
export const ide: any = stub
export const inbox: any = stub
export const includeAttribution: any = stub
export const includeHookEvents: any = stub
export const includePartialMessages: any = stub
export const initialAgentColor: any = stub
export const initialAgentName: any = stub
export const initialContentReplacements: any = stub
export const initialFileHistorySnapshots: any = stub
export const initialMessage: any = stub
export const initialMessages: any = stub
export const initialPermissionModeFromCLI: any = stub
export const initialState: any = stub
export const initialTools: any = stub
export const initializeGrowthBook: any = stub
export const initializeToolPermissionContext: any = stub
export const inputFormat: any = stub
export const installationStatus: any = stub
export const isAdvisorEnabled: any = stub
export const isAutoUpdaterDisabled: any = stub
export const isBareMode: any = stub
export const isBriefOnly: any = stub
export const isBuiltInAgent: any = stub
export const isAstroAISubscriber: any = stub
export const isCustomAgent: any = stub
export const isDefaultPermissionModeAuto: any = stub
export const isENOENT: any = stub
export const isEnvTruthy: any = stub
export const isFastModeEnabled: any = stub
export const isTmuxAvailable: any = stub
export const isValidAdvisorModel: any = stub
export const is_auto_bash_allowed_if_sandbox_enabled: any = stub
export const is_native_binary: any = stub
export const jsonSchema: any = stub
export const kairosEnabled: any = stub
export const keys: any = stub
export const label: any = stub
export const launchAssistantSessionChooser: any = stub
export const launchInvalidSettingsDialog: any = stub
export const launchResumeChooser: any = stub
export const launchSnapshotUpdateDialog: any = stub
export const launchTeleportRepoMismatchDialog: any = stub
export const loadPolicyLimits: any = stub
export const loadTranscriptFromFile: any = stub
export const local: any = stub
export const localVersion: any = stub
export const mainLoopModel: any = stub
export const mainLoopModelForSession: any = stub
export const mainThreadAgentDefinition: any = stub
export const managedNames: any = stub
export const marketplace: any = stub
export const maxBudgetUsd: any = stub
export const maxTurns: any = stub
export const mcp: any = stub
export const mcpClientCount: any = stub
export const mcpClients: any = stub
export const mcpConfig: any = stub
export const medium: any = stub
export const migrationVersion: any = stub
export const mode: any = stub
export const modeIsBypass: any = stub
export const model: any = stub
export const name: any = stub
export const needsRefresh: any = stub
export const normalizeModelStringForAPI: any = stub
export const notification: any = stub
export const notifications: any = stub
export const numAllowedTools: any = stub
export const numDisallowedTools: any = stub
export const numStartups: any = stub
export const oauthToken: any = stub
export const onExit: any = stub
export const opts: any = stub
export const outputFormat: any = stub
export const parentSessionId: any = stub
export const parseMcpConfig: any = stub
export const parseToolListFromCLI: any = stub
export const passes: any = stub
export const pendingSandboxRequest: any = stub
export const pendingWorkerRequest: any = stub
export const permissionMode: any = stub
export const permissionPromptToolName: any = stub
export const planModeRequired: any = stub
export const plugin: any = stub
export const pluginReconnectKey: any = stub
export const plugins: any = stub
export const prefers_reduced_motion: any = stub
export const prefetchAwsCredentialsAndBedRockInfoIfSafe: any = stub
export const prefetchFastModeStatus: any = stub
export const prefetchGcpCredentialsIfSafe: any = stub
export const prev: any = stub
export const print: any = stub
export const priority: any = stub
export const processMessagesForTeleportResume: any = stub
export const profileCheckpoint: any = stub
export const project: any = stub
export const promptId: any = stub
export const promptSuggestion: any = stub
export const promptSuggestionEnabled: any = stub
export const pruneShellSnapshots: any = stub
export const queue: any = stub
export const refreshPolicyLimits: any = stub
export const registerSession: any = stub
export const remoteAgentTaskSuggestions: any = stub
export const remoteBackgroundTaskCount: any = stub
export const remoteConnectionStatus: any = stub
export const remoteSessionUrl: any = stub
export const removeDangerousPermissions: any = stub
export const renderAndRun: any = stub
export const replBridgeConnectUrl: any = stub
export const replBridgeConnected: any = stub
export const replBridgeEnabled: any = stub
export const replBridgeEnvironmentId: any = stub
export const replBridgeError: any = stub
export const replBridgeExplicit: any = stub
export const replBridgeInitialName: any = stub
export const replBridgeOutboundOnly: any = stub
export const replBridgeReconnecting: any = stub
export const replBridgeSessionActive: any = stub
export const replBridgeSessionId: any = stub
export const replBridgeSessionUrl: any = stub
export const replayUserMessages: any = stub
export const resources: any = stub
export const resume: any = stub
export const resumeSessionAt: any = stub
export const resume_duration_ms: any = stub
export const rewindFiles: any = stub
export const sandbox_enabled: any = stub
export const saveAgentSetting: any = stub
export const saveMode: any = stub
export const scope: any = stub
export const sdkMcpConfigs: any = stub
export const sdkUrl: any = stub
export const searchSessionsByCustomTitle: any = stub
export const selectedIPAgentIndex: any = stub
export const selectedIndex: any = stub
export const sessionHooks: any = stub
export const sessionId: any = stub
export const setAdditionalDirectoriesForAstroMd: any = stub
export const setAllowedChannels: any = stub
export const setAllowedSettingSources: any = stub
export const setChromeFlagOverride: any = stub
export const setClientType: any = stub
export const setCwdState: any = stub
export const setDirectConnectServerUrl: any = stub
export const setFlagSettingsPath: any = stub
export const setInitialMainLoopModel: any = stub
export const setInlinePlugins: any = stub
export const setIsInteractive: any = stub
export const setIsRemoteMode: any = stub
export const setKairosActive: any = stub
export const setMainLoopModelOverride: any = stub
export const setMainThreadAgentType: any = stub
export const setOriginalCwd: any = stub
export const setQuestionPreviewFormat: any = stub
export const setSdkBetas: any = stub
export const setSessionBypassPermissionsMode: any = stub
export const setSessionPersistenceDisabled: any = stub
export const setSessionSource: any = stub
export const setUserMsgOptIn: any = stub
export const settings_file: any = stub
export const setupTrigger: any = stub
export const shouldAutoEnableAstroInChrome: any = stub
export const showRemoteCallout: any = stub
export const showTeammateMessagePreview: any = stub
export const shownAt: any = stub
export const skillImprovement: any = stub
export const skills: any = stub
export const skipWebFetchPreflight: any = stub
export const snapshotSequence: any = stub
export const snapshotTimestamp: any = stub
export const sortOptions: any = stub
export const source: any = stub
export const speculation: any = stub
export const speculationSessionTimeSavedMs: any = stub
export const sshSession: any = stub
export const startupPrefetchedAt: any = stub
export const stats: any = stub
export const statusLineText: any = stub
export const strictMcpConfig: any = stub
export const stripDangerousPermissionsForAutoMode: any = stub
export const subscriptionType: any = stub
export const systemPrompt: any = stub
export const systemPromptFlag: any = stub
export const taskBudget: any = stub
export const taskListId: any = stub
export const tasks: any = stub
export const teamName: any = stub
export const teleport: any = stub
export const teleportToRemoteWithErrorHandling: any = stub
export const text: any = stub
export const the: any = stub
export const thinkingConfig: any = stub
export const thinkingEnabled: any = stub
export const tips: any = stub
export const tmuxEnabled: any = stub
export const todos: any = stub
export const toolPermissionContext: any = stub
export const tools: any = stub
export const trackedFiles: any = stub
export const transcriptPath: any = stub
export const trimmedSettings: any = stub
export const type: any = stub
export const userSpecifiedModel: any = stub
export const validateGitState: any = stub
export const value: any = stub
export const verbose: any = stub
export const viewSelectionMode: any = stub
export const workerSandboxPermissions: any = stub
export const workload: any = stub
export const worktreeCount: any = stub
export const worktreeEnabled: any = stub
export const worktreeName: any = stub
export const worktreePRNumber: any = stub
export const worktree_count: any = stub

export default stub
