/*
 * AUTO-GENERATED COMPATIBILITY STUB.
 *
 * The recovered source tree imports this module, but the original file is
 * absent from this checkout. This stub only exists so local tooling can
 * resolve modules; it is not a replacement for the original implementation.
 */

type StubCallable = ((...args: unknown[]) => unknown) & Record<PropertyKey, unknown>

const createStub = (label: string): StubCallable => {
  const target = function compatibilityStub() {
    throw new Error(`Missing original implementation for src/services/compact/cachedMicrocompact.ts (${label})`)
  } as StubCallable
  return new Proxy(target, {
    get(current, prop) {
      if (prop === 'then') return undefined
      if (prop === Symbol.toStringTag) return 'CompatibilityStub'
      if (prop in current) return current[prop]
      return createStub(`${label}.${String(prop)}`)
    },
    apply() {
      throw new Error(`Missing original implementation for src/services/compact/cachedMicrocompact.ts (${label})`)
    },
    construct() {
      throw new Error(`Missing original implementation for src/services/compact/cachedMicrocompact.ts (${label})`)
    },
  })
}

const stub = createStub("src/services/compact/cachedMicrocompact.ts")

export type APIError = any
export type APIUserAbortError = any
export type BetaContentBlock = any
export type BetaContentBlockParam = any
export type BetaImageBlockParam = any
export type BetaJSONOutputFormat = any
export type BetaMessage = any
export type BetaMessageDeltaUsage = any
export type BetaMessageParam = any
export type BetaMessageStreamParams = any
export type BetaOutputConfig = any
export type BetaRawMessageStreamEvent = any
export type BetaRequestDocumentBlock = any
export type BetaStopReason = any
export type BetaToolChoiceAuto = any
export type BetaToolChoiceTool = any
export type BetaToolResultBlockParam = any
export type BetaToolUnion = any
export type BetaUsage = any
export type CONTEXT_1M_BETA_HEADER = any
export type CONTEXT_MANAGEMENT_BETA_HEADER = any
export type CUSTOM_OFF_SWITCH_MESSAGE = any
export type ConnectorTextDelta = any
export type EFFORT_BETA_HEADER = any
export type FAST_MODE_BETA_HEADER = any
export type FallbackTriggeredError = any
export type GlobalCacheStrategy = any
export type LLMRequestNewContext = any
export type MAX_NON_STREAMING_TOKENS = any
export type Message = any
export type NonNullableUsage = any
export type PROMPT_CACHING_SCOPE_BETA_HEADER = any
export type QueryChainTracking = any
export type REDACT_THINKING_BETA_HEADER = any
export type RetryContext = any
export type STRUCTURED_OUTPUTS_BETA_HEADER = any
export type StreamEvent = any
export type SystemAPIErrorMessage = any
export type SystemPrompt = any
export type TASK_BUDGETS_BETA_HEADER = any
export type TOOL_SEARCH_TOOL_NAME = any
export type ThinkingConfig = any
export type Tool = any
export type ToolPermissionContext = any
export type Tools = any
export type UserMessage = any
export type addCache = any
export type attempt = any
export type betas = any
export type captureRequest = any
export type checkResponseForCacheBreak = any
export type content = any
export type createUserMessage = any
export type device_id = any
export type effort_override = any
export type enablePromptCaching = any
export type ensureToolResultPairing = any
export type error = any
export type extraBodyParams = any
export type extractQuotaStatusFromError = any
export type extractQuotaStatusFromHeaders = any
export type extract_memories = any
export type fallbackModel = any
export type fetchOverride = any
export type getAssistantMessageFromError = any
export type getCLISyspromptPrefix = any
export type getCacheEditingHeaderLatched = any
export type getCachedMCConfig = any
export type getDefaultSonnetModel = any
export type getErrorMessageIfRefusal = any
export type getExperimentAdvisorModels = any
export type getFastModeHeaderLatched = any
export type getLastApiCompletionTimestamp = any
export type getMergedBetas = any
export type getModelBetas = any
export type getModelMaxOutputTokens = any
export type getPinnedCacheEdits = any
export type getPromptCache1hAllowlist = any
export type getPromptCache1hEligible = any
export type getSessionId = any
export type getSmallFastModel = any
export type getSonnet1mExpTreatmentEnabled = any
export type getThinkingClearLatched = any
export type initialConsecutive529Errors = any
export type is529Error = any
export type isAdvisorEnabled = any
export type isConnectorTextBlock = any
export type isDeferredTool = any
export type isDeferredToolsDeltaEnabled = any
export type isFastModeCooldown = any
export type isFastModeEnabled = any
export type isFastModeSupportedByModel = any
export type isFirstPartyAnthropicBaseUrl = any
export type isModelSupportedForCacheEditing = any
export type isNonCustomOpusModel = any
export type isNonInteractiveSession = any
export type isToolSearchEnabled = any
export type isValidAdvisorModel = any
export type limit = any
export type logAPIError = any
export type logAPIPrefix = any
export type logAPIQuery = any
export type logAPISuccessAndDuration = any
export type logEvent = any
export type markToolsSentToAPIState = any
export type maxOutputTokens = any
export type maxRetries = any
export type max_tokens = any
export type message = any
export type messages = any
export type metadata = any
export type model = any
export type modelSupportsAdvisor = any
export type modelSupportsStructuredOutputs = any
export type modelSupportsThinking = any
export type normalizeContentFromAPI = any
export type normalizeMessagesForAPI = any
export type onAttempt = any
export type options = any
export type outputConfig = any
export type paramsFromContext = any
export type parseUserSpecifiedModel = any
export type pinCacheEdits = any
export type querySource = any
export type recordPromptState = any
export type request_id = any
export type retryOptions = any
export type session_id = any
export type setAfkModeHeaderLatched = any
export type setCacheEditingHeaderLatched = any
export type setFastModeHeaderLatched = any
export type setLastMainRequestId = any
export type setPromptCache1hAllowlist = any
export type setPromptCache1hEligible = any
export type setThinkingClearLatched = any
export type shouldIncludeFirstPartyOnlyBetas = any
export type shouldUseGlobalCacheScope = any
export type side_question = any
export type signal = any
export type so = any
export type source = any
export type splitSysPromptPrefix = any
export type start = any
export type startLLMRequestSpan = any
export type stopSessionActivity = any
export type stripAdvisorBlocks = any
export type stripCallerFieldFromAssistantMessage = any
export type stripToolReferenceBlocksFromUserMessage = any
export type subagent = any
export type systemPrompt = any
export type temperature = any
export type text = any
export type thinkingConfig = any
export type timeout = any
export type timeout_ms = any
export type toolMatchesName = any
export type toolToAPISchema = any
export type tools = any
export type total = any
export type withRetry = any

export const APIError: any = stub
export const APIUserAbortError: any = stub
export const BetaContentBlock: any = stub
export const BetaContentBlockParam: any = stub
export const BetaImageBlockParam: any = stub
export const BetaJSONOutputFormat: any = stub
export const BetaMessage: any = stub
export const BetaMessageDeltaUsage: any = stub
export const BetaMessageParam: any = stub
export const BetaMessageStreamParams: any = stub
export const BetaOutputConfig: any = stub
export const BetaRawMessageStreamEvent: any = stub
export const BetaRequestDocumentBlock: any = stub
export const BetaStopReason: any = stub
export const BetaToolChoiceAuto: any = stub
export const BetaToolChoiceTool: any = stub
export const BetaToolResultBlockParam: any = stub
export const BetaToolUnion: any = stub
export const BetaUsage: any = stub
export const CONTEXT_1M_BETA_HEADER: any = stub
export const CONTEXT_MANAGEMENT_BETA_HEADER: any = stub
export const CUSTOM_OFF_SWITCH_MESSAGE: any = stub
export const ConnectorTextDelta: any = stub
export const EFFORT_BETA_HEADER: any = stub
export const FAST_MODE_BETA_HEADER: any = stub
export const FallbackTriggeredError: any = stub
export const GlobalCacheStrategy: any = stub
export const LLMRequestNewContext: any = stub
export const MAX_NON_STREAMING_TOKENS: any = stub
export const Message: any = stub
export const NonNullableUsage: any = stub
export const PROMPT_CACHING_SCOPE_BETA_HEADER: any = stub
export const QueryChainTracking: any = stub
export const REDACT_THINKING_BETA_HEADER: any = stub
export const RetryContext: any = stub
export const STRUCTURED_OUTPUTS_BETA_HEADER: any = stub
export const StreamEvent: any = stub
export const SystemAPIErrorMessage: any = stub
export const SystemPrompt: any = stub
export const TASK_BUDGETS_BETA_HEADER: any = stub
export const TOOL_SEARCH_TOOL_NAME: any = stub
export const ThinkingConfig: any = stub
export const Tool: any = stub
export const ToolPermissionContext: any = stub
export const Tools: any = stub
export const UserMessage: any = stub
export const addCache: any = stub
export const attempt: any = stub
export const betas: any = stub
export const captureRequest: any = stub
export const checkResponseForCacheBreak: any = stub
export const content: any = stub
export const createUserMessage: any = stub
export const device_id: any = stub
export const effort_override: any = stub
export const enablePromptCaching: any = stub
export const ensureToolResultPairing: any = stub
export const error: any = stub
export const extraBodyParams: any = stub
export const extractQuotaStatusFromError: any = stub
export const extractQuotaStatusFromHeaders: any = stub
export const extract_memories: any = stub
export const fallbackModel: any = stub
export const fetchOverride: any = stub
export const getAssistantMessageFromError: any = stub
export const getCLISyspromptPrefix: any = stub
export const getCacheEditingHeaderLatched: any = stub
export const getCachedMCConfig: any = stub
export const getDefaultSonnetModel: any = stub
export const getErrorMessageIfRefusal: any = stub
export const getExperimentAdvisorModels: any = stub
export const getFastModeHeaderLatched: any = stub
export const getLastApiCompletionTimestamp: any = stub
export const getMergedBetas: any = stub
export const getModelBetas: any = stub
export const getModelMaxOutputTokens: any = stub
export const getPinnedCacheEdits: any = stub
export const getPromptCache1hAllowlist: any = stub
export const getPromptCache1hEligible: any = stub
export const getSessionId: any = stub
export const getSmallFastModel: any = stub
export const getSonnet1mExpTreatmentEnabled: any = stub
export const getThinkingClearLatched: any = stub
export const initialConsecutive529Errors: any = stub
export const is529Error: any = stub
export const isAdvisorEnabled: any = stub
export const isConnectorTextBlock: any = stub
export const isDeferredTool: any = stub
export const isDeferredToolsDeltaEnabled: any = stub
export const isFastModeCooldown: any = stub
export const isFastModeEnabled: any = stub
export const isFastModeSupportedByModel: any = stub
export const isFirstPartyAnthropicBaseUrl: any = stub
export const isModelSupportedForCacheEditing: any = stub
export const isNonCustomOpusModel: any = stub
export const isNonInteractiveSession: any = stub
export const isToolSearchEnabled: any = stub
export const isValidAdvisorModel: any = stub
export const limit: any = stub
export const logAPIError: any = stub
export const logAPIPrefix: any = stub
export const logAPIQuery: any = stub
export const logAPISuccessAndDuration: any = stub
export const logEvent: any = stub
export const markToolsSentToAPIState: any = stub
export const maxOutputTokens: any = stub
export const maxRetries: any = stub
export const max_tokens: any = stub
export const message: any = stub
export const messages: any = stub
export const metadata: any = stub
export const model: any = stub
export const modelSupportsAdvisor: any = stub
export const modelSupportsStructuredOutputs: any = stub
export const modelSupportsThinking: any = stub
export const normalizeContentFromAPI: any = stub
export const normalizeMessagesForAPI: any = stub
export const onAttempt: any = stub
export const options: any = stub
export const outputConfig: any = stub
export const paramsFromContext: any = stub
export const parseUserSpecifiedModel: any = stub
export const pinCacheEdits: any = stub
export const querySource: any = stub
export const recordPromptState: any = stub
export const request_id: any = stub
export const retryOptions: any = stub
export const session_id: any = stub
export const setAfkModeHeaderLatched: any = stub
export const setCacheEditingHeaderLatched: any = stub
export const setFastModeHeaderLatched: any = stub
export const setLastMainRequestId: any = stub
export const setPromptCache1hAllowlist: any = stub
export const setPromptCache1hEligible: any = stub
export const setThinkingClearLatched: any = stub
export const shouldIncludeFirstPartyOnlyBetas: any = stub
export const shouldUseGlobalCacheScope: any = stub
export const side_question: any = stub
export const signal: any = stub
export const so: any = stub
export const source: any = stub
export const splitSysPromptPrefix: any = stub
export const start: any = stub
export const startLLMRequestSpan: any = stub
export const stopSessionActivity: any = stub
export const stripAdvisorBlocks: any = stub
export const stripCallerFieldFromAssistantMessage: any = stub
export const stripToolReferenceBlocksFromUserMessage: any = stub
export const subagent: any = stub
export const systemPrompt: any = stub
export const temperature: any = stub
export const text: any = stub
export const thinkingConfig: any = stub
export const timeout: any = stub
export const timeout_ms: any = stub
export const toolMatchesName: any = stub
export const toolToAPISchema: any = stub
export const tools: any = stub
export const total: any = stub
export const withRetry: any = stub

export default stub
