/*
 * AUTO-GENERATED COMPATIBILITY STUB.
 *
 * The recovered source tree imports this module, but the original file is
 * absent from this checkout. This stub only exists so local tooling can
 * resolve modules; it is not a replacement for the original implementation.
 */

type StubCallable = ((...args: unknown[]) => unknown) & Record<PropertyKey, unknown>

const createStub = (label: string): StubCallable => {
  const target = function compatibilityStub() {
    throw new Error(`Missing original implementation for src/services/compact/snipProjection.ts (${label})`)
  } as StubCallable
  return new Proxy(target, {
    get(current, prop) {
      if (prop === 'then') return undefined
      if (prop === Symbol.toStringTag) return 'CompatibilityStub'
      if (prop in current) return current[prop]
      return createStub(`${label}.${String(prop)}`)
    },
    apply() {
      throw new Error(`Missing original implementation for src/services/compact/snipProjection.ts (${label})`)
    },
    construct() {
      throw new Error(`Missing original implementation for src/services/compact/snipProjection.ts (${label})`)
    },
  })
}

const stub = createStub("src/services/compact/snipProjection.ts")

export type AttachmentMessage = any
export type Background = any
export type BetaContentBlock = any
export type BetaMessage = any
export type BetaRedactedThinkingBlock = any
export type BetaThinkingBlock = any
export type BetaToolUseBlock = any
export type CANCEL_MESSAGE = any
export type COMMAND_MESSAGE_TAG = any
export type COMMAND_NAME_TAG = any
export type CollapsedReadSearchGroup = any
export type ContentBlockParam = any
export type GLOB_TOOL_NAME = any
export type GroupedToolUseMessage = any
export type HookAttachment = any
export type HookPermissionDecisionAttachment = any
export type INTERRUPT_MESSAGE_FOR_TOOL_USE = any
export type LOCAL_COMMAND_CAVEAT_TAG = any
export type LOCAL_COMMAND_STDOUT_TAG = any
export type MAX_LINES_TO_READ = any
export type Message = any
export type MessageOrigin = any
export type NO_RESPONSE_REQUESTED = any
export type NormalizedAssistantMessage = any
export type NormalizedMessage = any
export type NormalizedUserMessage = any
export type Output = any
export type PartialCompactDirection = any
export type ProgressMessage = any
export type REJECT_MESSAGE = any
export type RedactedThinkingBlock = any
export type RedactedThinkingBlockParam = any
export type RequestStartEvent = any
export type SDKAssistantMessageError = any
export type StopHookInfo = any
export type StreamEvent = any
export type SystemAPIErrorMessage = any
export type SystemAgentsKilledMessage = any
export type SystemApiMetricsMessage = any
export type SystemAwaySummaryMessage = any
export type SystemBridgeStatusMessage = any
export type SystemCompactBoundaryMessage = any
export type SystemInformationalMessage = any
export type SystemLocalCommandMessage = any
export type SystemMemorySavedMessage = any
export type SystemMessage = any
export type SystemMessageLevel = any
export type SystemMicrocompactBoundaryMessage = any
export type SystemPermissionRetryMessage = any
export type SystemScheduledTaskFireMessage = any
export type SystemStopHookSummaryMessage = any
export type SystemTurnDurationMessage = any
export type TOOL_REFERENCE_TURN_BOUNDARY = any
export type TextBlockParam = any
export type ThinkingBlock = any
export type ThinkingBlockParam = any
export type TombstoneMessage = any
export type Tool = any
export type ToolResultBlockParam = any
export type ToolUseBlock = any
export type ToolUseBlockParam = any
export type ToolUseSummaryMessage = any
export type Tools = any
export type UserMessage = any
export type _ = any
export type addMargin = any
export type advisorModel = any
export type agentId = any
export type apiError = any
export type args = any
export type availableToolNames = any
export type b = any
export type blocks = any
export type budgetLimit = any
export type budgetNudges = any
export type budgetTokens = any
export type c = any
export type cache_creation = any
export type cache_creation_input_tokens = any
export type cache_read_input_tokens = any
export type cause = any
export type classifierCount = any
export type classifierDurationMs = any
export type classifierModel = any
export type clearedAttachmentUUIDs = any
export type commands = any
export type compactMetadata = any
export type compactedToolIds = any
export type concat = any
export type configWriteCount = any
export type container = any
export type containerWidth = any
export type content = any
export type contentBlock = any
export type context_management = any
export type data = any
export type description = any
export type document = any
export type durationMs = any
export type ephemeral_5m_input_tokens = any
export type error = any
export type errorDetails = any
export type erroredToolUseIDs = any
export type getFeatureValue_CACHED_MAY_BE_STALE = any
export type getPdfInvalidErrorMessage = any
export type getPdfPasswordProtectedErrorMessage = any
export type getPdfTooLargeErrorMessage = any
export type getPlanModeV2ExploreAgentCount = any
export type getRequestTooLargeErrorMessage = any
export type hasOutput = any
export type hook = any
export type hookCount = any
export type hookDurationMs = any
export type hookErrors = any
export type hookEvent = any
export type hookInfos = any
export type hookLabel = any
export type id = any
export type image = any
export type imagePasteIds = any
export type inProgressHookCounts = any
export type inProgressToolUseIDs = any
export type index = any
export type inference_geo = any
export type input = any
export type inputLen = any
export type interrupted = any
export type isActiveCollapsedGroup = any
export type isApiErrorMessage = any
export type isCompactSummary = any
export type isMeta = any
export type isP50 = any
export type isPlanModeInterviewPhaseEnabled = any
export type isStreaming = any
export type isToolSearchEnabledOptimistic = any
export type isTranscriptMode = any
export type isUserContinuation = any
export type isVirtual = any
export type isVisibleInTranscriptOnly = any
export type is_error = any
export type iterations = any
export type lastMessage = any
export type lastThinkingBlockId = any
export type level = any
export type logEvent = any
export type lookups = any
export type maxRetries = any
export type mcp = any
export type mcpMeta = any
export type memoryHeader = any
export type message = any
export type messageCount = any
export type messages = any
export type messagesSummarized = any
export type microcompactMetadata = any
export type mode = any
export type model = any
export type name = any
export type normalizedInput = any
export type normalizedMessage = any
export type normalizedMessageCount = any
export type not = any
export type onMessage = any
export type onOpenRateLimitOptions = any
export type onSetStreamMode = any
export type onStreamingToolUses = any
export type onUpdateLength = any
export type origin = any
export type otps = any
export type output_tokens = any
export type pages = any
export type parentToolUseID = any
export type permissionMode = any
export type postHooks = any
export type preHooks = any
export type preTokens = any
export type precedingInputBlocks = any
export type preferences = any
export type preventedContinuation = any
export type progressMessagesByToolUseID = any
export type progressMessagesForMessage = any
export type renamed = any
export type requestId = any
export type resolvedDisplay = any
export type resolvedHookCounts = any
export type resolvedToolUseIDs = any
export type retryAttempt = any
export type retryInMs = any
export type role = any
export type separator = any
export type server_tool_use = any
export type service_tier = any
export type shouldAnimate = any
export type shouldShowDot = any
export type smooshed = any
export type so = any
export type sourceToolAssistantUUID = any
export type speed = any
export type stderr = any
export type stopReason = any
export type stop_reason = any
export type stop_sequence = any
export type streamingEndedAt = any
export type style = any
export type subtype = any
export type summarizeMetadata = any
export type syntheticStreamingToolUseMessages = any
export type tagName = any
export type text = any
export type timestamp = any
export type tokensSaved = any
export type toolCount = any
export type toolDurationMs = any
export type toolMatchesName = any
export type toolResult = any
export type toolResultByToolUseID = any
export type toolUseByToolUseID = any
export type toolUseID = any
export type toolUseResult = any
export type tool_use_id = any
export type tools = any
export type totalDurationMs = any
export type tradeoffs = any
export type ttftMs = any
export type turnDurationMs = any
export type type = any
export type unparsedToolInput = any
export type upgradeNudge = any
export type url = any
export type usage = any
export type userContext = any
export type utilities = any
export type uuid = any
export type verbose = any
export type web_fetch_requests = any
export type web_search = any
export type width = any
export type writtenPaths = any

export const AttachmentMessage: any = stub
export const Background: any = stub
export const BetaContentBlock: any = stub
export const BetaMessage: any = stub
export const BetaRedactedThinkingBlock: any = stub
export const BetaThinkingBlock: any = stub
export const BetaToolUseBlock: any = stub
export const CANCEL_MESSAGE: any = stub
export const COMMAND_MESSAGE_TAG: any = stub
export const COMMAND_NAME_TAG: any = stub
export const CollapsedReadSearchGroup: any = stub
export const ContentBlockParam: any = stub
export const GLOB_TOOL_NAME: any = stub
export const GroupedToolUseMessage: any = stub
export const HookAttachment: any = stub
export const HookPermissionDecisionAttachment: any = stub
export const INTERRUPT_MESSAGE_FOR_TOOL_USE: any = stub
export const LOCAL_COMMAND_CAVEAT_TAG: any = stub
export const LOCAL_COMMAND_STDOUT_TAG: any = stub
export const MAX_LINES_TO_READ: any = stub
export const Message: any = stub
export const MessageOrigin: any = stub
export const NO_RESPONSE_REQUESTED: any = stub
export const NormalizedAssistantMessage: any = stub
export const NormalizedMessage: any = stub
export const NormalizedUserMessage: any = stub
export const Output: any = stub
export const PartialCompactDirection: any = stub
export const ProgressMessage: any = stub
export const REJECT_MESSAGE: any = stub
export const RedactedThinkingBlock: any = stub
export const RedactedThinkingBlockParam: any = stub
export const RequestStartEvent: any = stub
export const SDKAssistantMessageError: any = stub
export const StopHookInfo: any = stub
export const StreamEvent: any = stub
export const SystemAPIErrorMessage: any = stub
export const SystemAgentsKilledMessage: any = stub
export const SystemApiMetricsMessage: any = stub
export const SystemAwaySummaryMessage: any = stub
export const SystemBridgeStatusMessage: any = stub
export const SystemCompactBoundaryMessage: any = stub
export const SystemInformationalMessage: any = stub
export const SystemLocalCommandMessage: any = stub
export const SystemMemorySavedMessage: any = stub
export const SystemMessage: any = stub
export const SystemMessageLevel: any = stub
export const SystemMicrocompactBoundaryMessage: any = stub
export const SystemPermissionRetryMessage: any = stub
export const SystemScheduledTaskFireMessage: any = stub
export const SystemStopHookSummaryMessage: any = stub
export const SystemTurnDurationMessage: any = stub
export const TOOL_REFERENCE_TURN_BOUNDARY: any = stub
export const TextBlockParam: any = stub
export const ThinkingBlock: any = stub
export const ThinkingBlockParam: any = stub
export const TombstoneMessage: any = stub
export const Tool: any = stub
export const ToolResultBlockParam: any = stub
export const ToolUseBlock: any = stub
export const ToolUseBlockParam: any = stub
export const ToolUseSummaryMessage: any = stub
export const Tools: any = stub
export const UserMessage: any = stub
export const _: any = stub
export const addMargin: any = stub
export const advisorModel: any = stub
export const agentId: any = stub
export const apiError: any = stub
export const args: any = stub
export const availableToolNames: any = stub
export const b: any = stub
export const blocks: any = stub
export const budgetLimit: any = stub
export const budgetNudges: any = stub
export const budgetTokens: any = stub
export const c: any = stub
export const cache_creation: any = stub
export const cache_creation_input_tokens: any = stub
export const cache_read_input_tokens: any = stub
export const cause: any = stub
export const classifierCount: any = stub
export const classifierDurationMs: any = stub
export const classifierModel: any = stub
export const clearedAttachmentUUIDs: any = stub
export const commands: any = stub
export const compactMetadata: any = stub
export const compactedToolIds: any = stub
export const concat: any = stub
export const configWriteCount: any = stub
export const container: any = stub
export const containerWidth: any = stub
export const content: any = stub
export const contentBlock: any = stub
export const context_management: any = stub
export const data: any = stub
export const description: any = stub
export const document: any = stub
export const durationMs: any = stub
export const ephemeral_5m_input_tokens: any = stub
export const error: any = stub
export const errorDetails: any = stub
export const erroredToolUseIDs: any = stub
export const getFeatureValue_CACHED_MAY_BE_STALE: any = stub
export const getPdfInvalidErrorMessage: any = stub
export const getPdfPasswordProtectedErrorMessage: any = stub
export const getPdfTooLargeErrorMessage: any = stub
export const getPlanModeV2ExploreAgentCount: any = stub
export const getRequestTooLargeErrorMessage: any = stub
export const hasOutput: any = stub
export const hook: any = stub
export const hookCount: any = stub
export const hookDurationMs: any = stub
export const hookErrors: any = stub
export const hookEvent: any = stub
export const hookInfos: any = stub
export const hookLabel: any = stub
export const id: any = stub
export const image: any = stub
export const imagePasteIds: any = stub
export const inProgressHookCounts: any = stub
export const inProgressToolUseIDs: any = stub
export const index: any = stub
export const inference_geo: any = stub
export const input: any = stub
export const inputLen: any = stub
export const interrupted: any = stub
export const isActiveCollapsedGroup: any = stub
export const isApiErrorMessage: any = stub
export const isCompactSummary: any = stub
export const isMeta: any = stub
export const isP50: any = stub
export const isPlanModeInterviewPhaseEnabled: any = stub
export const isStreaming: any = stub
export const isToolSearchEnabledOptimistic: any = stub
export const isTranscriptMode: any = stub
export const isUserContinuation: any = stub
export const isVirtual: any = stub
export const isVisibleInTranscriptOnly: any = stub
export const is_error: any = stub
export const iterations: any = stub
export const lastMessage: any = stub
export const lastThinkingBlockId: any = stub
export const level: any = stub
export const logEvent: any = stub
export const lookups: any = stub
export const maxRetries: any = stub
export const mcp: any = stub
export const mcpMeta: any = stub
export const memoryHeader: any = stub
export const message: any = stub
export const messageCount: any = stub
export const messages: any = stub
export const messagesSummarized: any = stub
export const microcompactMetadata: any = stub
export const mode: any = stub
export const model: any = stub
export const name: any = stub
export const normalizedInput: any = stub
export const normalizedMessage: any = stub
export const normalizedMessageCount: any = stub
export const not: any = stub
export const onMessage: any = stub
export const onOpenRateLimitOptions: any = stub
export const onSetStreamMode: any = stub
export const onStreamingToolUses: any = stub
export const onUpdateLength: any = stub
export const origin: any = stub
export const otps: any = stub
export const output_tokens: any = stub
export const pages: any = stub
export const parentToolUseID: any = stub
export const permissionMode: any = stub
export const postHooks: any = stub
export const preHooks: any = stub
export const preTokens: any = stub
export const precedingInputBlocks: any = stub
export const preferences: any = stub
export const preventedContinuation: any = stub
export const progressMessagesByToolUseID: any = stub
export const progressMessagesForMessage: any = stub
export const renamed: any = stub
export const requestId: any = stub
export const resolvedDisplay: any = stub
export const resolvedHookCounts: any = stub
export const resolvedToolUseIDs: any = stub
export const retryAttempt: any = stub
export const retryInMs: any = stub
export const role: any = stub
export const separator: any = stub
export const server_tool_use: any = stub
export const service_tier: any = stub
export const shouldAnimate: any = stub
export const shouldShowDot: any = stub
export const smooshed: any = stub
export const so: any = stub
export const sourceToolAssistantUUID: any = stub
export const speed: any = stub
export const stderr: any = stub
export const stopReason: any = stub
export const stop_reason: any = stub
export const stop_sequence: any = stub
export const streamingEndedAt: any = stub
export const style: any = stub
export const subtype: any = stub
export const summarizeMetadata: any = stub
export const syntheticStreamingToolUseMessages: any = stub
export const tagName: any = stub
export const text: any = stub
export const timestamp: any = stub
export const tokensSaved: any = stub
export const toolCount: any = stub
export const toolDurationMs: any = stub
export const toolMatchesName: any = stub
export const toolResult: any = stub
export const toolResultByToolUseID: any = stub
export const toolUseByToolUseID: any = stub
export const toolUseID: any = stub
export const toolUseResult: any = stub
export const tool_use_id: any = stub
export const tools: any = stub
export const totalDurationMs: any = stub
export const tradeoffs: any = stub
export const ttftMs: any = stub
export const turnDurationMs: any = stub
export const type: any = stub
export const unparsedToolInput: any = stub
export const upgradeNudge: any = stub
export const url: any = stub
export const usage: any = stub
export const userContext: any = stub
export const utilities: any = stub
export const uuid: any = stub
export const verbose: any = stub
export const web_fetch_requests: any = stub
export const web_search: any = stub
export const width: any = stub
export const writtenPaths: any = stub

export default stub
