/*
 * AUTO-GENERATED COMPATIBILITY STUB.
 *
 * The recovered source tree imports this module, but the original file is
 * absent from this checkout. This stub only exists so local tooling can
 * resolve modules; it is not a replacement for the original implementation.
 */

type StubCallable = ((...args: unknown[]) => unknown) & Record<PropertyKey, unknown>

const createStub = (label: string): StubCallable => {
  const target = function compatibilityStub() {
    throw new Error(`Missing original implementation for src/types/message.ts (${label})`)
  } as StubCallable
  return new Proxy(target, {
    get(current, prop) {
      if (prop === 'then') return undefined
      if (prop === Symbol.toStringTag) return 'CompatibilityStub'
      if (prop in current) return current[prop]
      return createStub(`${label}.${String(prop)}`)
    },
    apply() {
      throw new Error(`Missing original implementation for src/types/message.ts (${label})`)
    },
    construct() {
      throw new Error(`Missing original implementation for src/types/message.ts (${label})`)
    },
  })
}

const stub = createStub("src/types/message.ts")

export type AGENT_COLORS = any
export type APIConnectionError = any
export type APIConnectionTimeoutError = any
export type APIError = any
export type APIUserAbortError = any
export type ASYNC_AGENT_ALLOWED_TOOLS = any
export type AgentDefinitionsResult = any
export type AgentId = any
export type AnalyticsMetadata_I_VERIFIED_THIS_IS_NOT_CODE_OR_FILEPATHS = any
export type AnalyticsMetadata_I_VERIFIED_THIS_IS_PII_TAGGED = any
export type AnyObject = any
export type AssistantMessage = any
export type AsyncHookJSONOutput = any
export type AttachmentMessage = any
export type AutoCompactTrackingState = any
export type Base64ImageSource = any
export type BetaContentBlock = any
export type BetaContentBlockParam = any
export type BetaImageBlockParam = any
export type BetaJSONOutputFormat = any
export type BetaMessage = any
export type BetaMessageDeltaUsage = any
export type BetaMessageParam = any
export type BetaMessageStreamParams = any
export type BetaOutputConfig = any
export type BetaRawMessageStreamEvent = any
export type BetaRequestDocumentBlock = any
export type BetaStopReason = any
export type BetaTool = any
export type BetaToolChoiceAuto = any
export type BetaToolChoiceTool = any
export type BetaToolResultBlockParam = any
export type BetaToolUnion = any
export type BetaUsage = any
export type BoundedUUIDSet = any
export type Box = any
export type BridgeConfig = any
export type BridgeFatalError = any
export type BridgePermissionResponse = any
export type BridgeState = any
export type BriefIdleStatus = any
export type COMMAND_MESSAGE_TAG = any
export type COMMAND_NAME_TAG = any
export type CUSTOM_AGENT_DISALLOWED_TOOLS = any
export type ClickEvent = any
export type CollapsedReadSearchGroup = any
export type CollapsibleMessage = any
export type Command = any
export type CommandBase = any
export type CommandResultDisplay = any
export type CommitKind = any
export type CompactMetadata = any
export type ConfigChangeHookInput = any
export type ConnectedMCPServer = any
export type ConnectorTextDelta = any
export type ContentBlockParam = any
export type ContextCollapseCommitEntry = any
export type ContextCollapseSnapshotEntry = any
export type CustomAgentDefinition = any
export type CwdChangedHookInput = any
export type DEFAULT_MAX_RESULT_SIZE_CHARS = any
export type DirectConnectSessionManager = any
export type ERROR_MESSAGE_INCOMPLETE_RESPONSE = any
export type ERROR_MESSAGE_NOT_ENOUGH_MESSAGES = any
export type ERROR_MESSAGE_USER_ABORT = any
export type ElicitRequestSchema = any
export type ElicitRequestURLParams = any
export type ElicitResult = any
export type ElicitationHookInput = any
export type ElicitationResultHookInput = any
export type Entry = any
export type EnvLessBridgeConfig = any
export type ErrorCode = any
export type ExitReason = any
export type FILE_UNCHANGED_STUB = any
export type FORK_DIRECTIVE_PREFIX = any
export type FetchLike = any
export type FileChangedHookInput = any
export type FileHistorySnapshotMessage = any
export type FilesApiConfig = any
export type GroupedToolUseMessage = any
export type HOOK_EVENTS = any
export type HistoryAuthCtx = any
export type HistoryPage = any
export type HookCallback = any
export type HookCallbackMatcher = any
export type HookCommand = any
export type HookInput = any
export type HookJSONOutput = any
export type HookResultMessage = any
export type IDLE_SPECULATION_STATE = any
export type IN_PROCESS_TEAMMATE_ALLOWED_TOOLS = any
export type ImageBlockParam = any
export type InstructionsLoadedHookInput = any
export type InvalidArgumentError = any
export type JSONRPCMessage = any
export type Key = any
export type LOCAL_COMMAND_STDOUT_TAG = any
export type ListPromptsResult = any
export type ListPromptsResultSchema = any
export type ListResourcesResultSchema = any
export type ListRootsRequestSchema = any
export type ListToolsResult = any
export type ListToolsResultSchema = any
export type LocalAgentTaskState = any
export type LocalJSXCommandContext = any
export type LogOption = any
export type MANUAL_COMPACT_BUFFER_TOKENS = any
export type MAX_TOOL_RESULTS_PER_MESSAGE_CHARS = any
export type MAX_TOOL_RESULT_BYTES = any
export type MCPServerConnection = any
export type MCPToolResult = any
export type MaxFileReadTokenExceededError = any
export type McpError = any
export type McpServerConfig = any
export type MemoryFileInfo = any
export type Message = any
export type MessageOrigin = any
export type MessageParam = any
export type NormalizedAssistantMessage = any
export type NormalizedMessage = any
export type NormalizedUserMessage = any
export type NotificationHookInput = any
export type Output = any
export type PartialCompactDirection = any
export type PermissionDeniedHookInput = any
export type PermissionRequestHookInput = any
export type PermissionRequestResult = any
export type PermissionUpdate = any
export type PersistedWorktreeSession = any
export type PluginHookMatcher = any
export type PostCompactHookInput = any
export type PostToolUseFailureHookInput = any
export type PostToolUseHookInput = any
export type PrAction = any
export type PreCompactHookInput = any
export type PreToolUseHookInput = any
export type ProgressMessage = any
export type ProgressTracker = any
export type PromptCommand = any
export type PromptMessage = any
export type PromptRequest = any
export type PromptResponse = any
export type QueryChainTracking = any
export type QueuedCommand = any
export type REFERENCE_MARK = any
export type REJECT_MESSAGE = any
export type ReactNode = any
export type RedactedThinkingBlock = any
export type RedactedThinkingBlockParam = any
export type RefObject = any
export type RemoteSessionConfig = any
export type RemoteSessionManager = any
export type RenderableMessage = any
export type ReplBridgeHandle = any
export type ReplBridgeTransport = any
export type RequestStartEvent = any
export type ResourceLink = any
export type ResumeEntrypoint = any
export type SDKAssistantMessage = any
export type SDKCompactBoundaryMessage = any
export type SDKControlResponse = any
export type SDKMessage = any
export type SDKPartialAssistantMessage = any
export type SDKPermissionDenial = any
export type SDKRateLimitInfo = any
export type SDKResultMessage = any
export type SDKStatus = any
export type SDKStatusMessage = any
export type SDKSystemMessage = any
export type SDKToolProgressMessage = any
export type SDKUserMessageReplay = any
export type SSEClientTransportOptions = any
export type STATUS_TAG = any
export type SUMMARY_TAG = any
export type SYSTEM_PROMPT_DYNAMIC_BOUNDARY = any
export type ScopedMcpServerConfig = any
export type SerializedMessage = any
export type ServerResource = any
export type SessionEndHookInput = any
export type SessionId = any
export type SessionStartHookInput = any
export type SetAppState = any
export type SetupHookInput = any
export type SkillHookMatcher = any
export type Span = any
export type SpeculationResult = any
export type SpeculationState = any
export type StopFailureHookInput = any
export type StopHookInfo = any
export type StopHookInput = any
export type StreamEvent = any
export type StreamableHTTPClientTransportOptions = any
export type StreamingThinking = any
export type StreamingToolUse = any
export type SubagentStartHookInput = any
export type SubagentStopHookInput = any
export type SyncHookJSONOutput = any
export type SystemAPIErrorMessage = any
export type SystemAgentsKilledMessage = any
export type SystemApiMetricsMessage = any
export type SystemAwaySummaryMessage = any
export type SystemBridgeStatusMessage = any
export type SystemCompactBoundaryMessage = any
export type SystemFileSnapshotMessage = any
export type SystemInformationalMessage = any
export type SystemLocalCommandMessage = any
export type SystemMemorySavedMessage = any
export type SystemMessage = any
export type SystemMessageLevel = any
export type SystemMicrocompactBoundaryMessage = any
export type SystemPermissionRetryMessage = any
export type SystemScheduledTaskFireMessage = any
export type SystemStopHookSummaryMessage = any
export type SystemThinkingMessage = any
export type SystemTurnDurationMessage = any
export type TASK_ID_TAG = any
export type TASK_NOTIFICATION_TAG = any
export type TOOL_SEARCH_TOOL_NAME = any
export type TOOL_USE_ID_TAG = any
export type Task = any
export type TaskCompletedHookInput = any
export type TaskCreatedHookInput = any
export type TeammateIdentity = any
export type TeammateIdleHookInput = any
export type TelemetrySafeError_I_VERIFIED_THIS_IS_NOT_CODE_OR_FILEPATHS = any
export type TeleportError = any
export type Text = any
export type TextBlockParam = any
export type ThinkingBlock = any
export type ThinkingBlockParam = any
export type TombstoneMessage = any
export type Tool = any
export type ToolCallProgress = any
export type ToolDef = any
export type ToolPermissionContext = any
export type ToolProgress = any
export type ToolProgressData = any
export type ToolResult = any
export type ToolResultBlockParam = any
export type ToolUseBlock = any
export type ToolUseBlockParam = any
export type ToolUseContext = any
export type ToolUseSummaryMessage = any
export type Tools = any
export type TranscriptMessage = any
export type Transport = any
export type UserMessage = any
export type UserPromptSubmitHookInput = any
export type ValidationResult = any
export type WORKTREE_BRANCH_TAG = any
export type WORKTREE_PATH_TAG = any
export type addToTurnHookDuration = any
export type appendMessageToLocalAgent = any
export type applyPermissionUpdates = any
export type asAgentId = any
export type asSessionId = any
export type buildCCRv2SdkUrl = any
export type buildSdkUrl = any
export type c = any
export type compactConversation = any
export type consumePostCompaction = any
export type copyFile = any
export type countTokensViaHaikuFallback = any
export type createActivityDescriptionResolver = any
export type createAgentsKilledMessage = any
export type createApiMetricsMessage = any
export type createAssistantMessage = any
export type createCacheSafeParams = any
export type createCommandInputMessage = any
export type createHash = any
export type createMemorySavedMessage = any
export type createProgressTracker = any
export type createSystemMessage = any
export type createToolStub = any
export type createTurnDurationMessage = any
export type createUserMessage = any
export type createV1ReplTransport = any
export type createV2ReplTransport = any
export type detectGitOperation = any
export type dirname = any
export type downloadSessionFiles = any
export type emitHookResponse = any
export type endHookSpan = any
export type enhanceSystemPromptWithEnvDetails = any
export type enqueueAgentNotification = any
export type exitTeammateView = any
export type exitWithMessage = any
export type expandPastedTextRefs = any
export type extractHttpStatus = any
export type extractSkillName = any
export type extractTitleText = any
export type extractToolInputForTelemetry = any
export type failAgentTask = any
export type fetchLatestEvents = any
export type fetchOlderEvents = any
export type fetchToolsForClient = any
export type fileHistoryCanRestore = any
export type fileHistoryEnabled = any
export type filterToolProgressMessages = any
export type findCommand = any
export type findToolByName = any
export type formatDescriptionWithSource = any
export type formatPastedTextRef = any
export type fstatSync = any
export type generateSandboxRequestId = any
export type getActiveAgentsFromList = any
export type getAgentDefinitionsWithOverrides = any
export type getAgentTranscriptPath = any
export type getBudgetContinuationCount = any
export type getCLISyspromptPrefix = any
export type getAstroAIOAuthTokens = any
export type getCodeEditToolDecisionCounter = any
export type getCommand = any
export type getCommandName = any
export type getCommands = any
export type getConditionalRulesForCwdLevelDirectory = any
export type getContentText = any
export type getCurrentTurnTokenBudget = any
export type getEffectiveContextWindowSize = any
export type getFeatureValue_CACHED_MAY_BE_STALE = any
export type getFileExtensionForAnalytics = any
export type getFileExtensionsFromBashCommand = any
export type getFormatDescription = any
export type getGlobalConfig = any
export type getInitialAdvisorSetting = any
export type getIsNonInteractiveSession = any
export type getKairosActive = any
export type getLargeOutputInstructions = any
export type getLastApiCompletionTimestamp = any
export type getLastAssistantMessage = any
export type getLastClassifierRequests = any
export type getLastInteractionTime = any
export type getLegacyToolNames = any
export type getMainThreadAgentType = any
export type getManagedAndUserConditionalRules = any
export type getMemoryFiles = any
export type getMemoryFilesForNestedDirectory = any
export type getMessagesAfterCompactBoundary = any
export type getOriginalCwd = any
export type getPastedTextRefNumLines = any
export type getPdfInvalidErrorMessage = any
export type getPdfPasswordProtectedErrorMessage = any
export type getPdfTooLargeErrorMessage = any
export type getPlanSlugCache = any
export type getProgressUpdate = any
export type getProjectRoot = any
export type getPromptId = any
export type getRegisteredHooks = any
export type getRemoteControlAtStartup = any
export type getRenderContext = any
export type getRequestTooLargeErrorMessage = any
export type getSdkBetas = any
export type getSessionId = any
export type getSessionProjectDir = any
export type getSettingsForSource = any
export type getSkillToolCommands = any
export type getSkillToolInfo = any
export type getStatsStore = any
export type getTaskListId = any
export type getTeleportedSessionInfo = any
export type getTokenCountFromTracker = any
export type getTotalAPIDuration = any
export type getTotalCost = any
export type getTotalDuration = any
export type getTotalInputTokens = any
export type getTotalLinesAdded = any
export type getTotalLinesRemoved = any
export type getTurnClassifierCount = any
export type getTurnClassifierDurationMs = any
export type getTurnHookCount = any
export type getTurnHookDurationMs = any
export type getTurnOutputTokens = any
export type getTurnToolCount = any
export type getTurnToolDurationMs = any
export type getWebSocketProxyAgent = any
export type getWebSocketProxyUrl = any
export type handleKeyEvent = any
export type handleMessageFromStream = any
export type handleOAuth401Error = any
export type handleServerControlRequest = any
export type handleTranscriptSelect = any
export type hasCommand = any
export type initializeGrowthBook = any
export type injectUserMessageToTeammate = any
export type invalidateSessionEnvCache = any
export type isAbsolute = any
export type isAdvisorEnabled = any
export type isAsyncHookJSONOutput = any
export type isAutoCompactEnabled = any
export type isAutoMemPath = any
export type isAutoMemoryEnabled = any
export type isAutoUpdaterDisabled = any
export type isBetaTracingEnabled = any
export type isBridgeSafeCommand = any
export type isBuiltInAgent = any
export type isAstroAISubscriber = any
export type isCodeEditingTool = any
export type isCompactBoundaryMessage = any
export type isConnectorTextBlock = any
export type isCustomAgent = any
export type isDeferredTool = any
export type isEligibleBridgeMessage = any
export type isExpiredErrorType = any
export type isFastModeEnabled = any
export type isFirstPartyAnthropicBaseUrl = any
export type isLocalAgentTask = any
export type isSessionEndMessage = any
export type isSessionPersistenceDisabled = any
export type isSuppressible403 = any
export type isSyncHookJSONOutput = any
export type isTerminalTaskStatus = any
export type isTodoV2Enabled = any
export type isToolDetailsLoggingEnabled = any
export type isValidAdvisorModel = any
export type join = any
export type killAsyncAgent = any
export type launchAssistantSessionChooser = any
export type launchInvalidSettingsDialog = any
export type launchResumeChooser = any
export type launchSnapshotUpdateDialog = any
export type launchTeleportRepoMismatchDialog = any
export type listTasks = any
export type loadPolicyLimits = any
export type logBridgeSkip = any
export type logEvent = any
export type makeResultMessage = any
export type markFirstTeleportMessageLogged = any
export type markTaskNotified = any
export type mcpContentNeedsTruncation = any
export type mcpInfoFromString = any
export type mcpToolDetailsForAnalytics = any
export type mergeFileStateCaches = any
export type mergeHookInstructions = any
export type mkdir = any
export type open = any
export type openSync = any
export type parse = any
export type parseAgentsFromJson = any
export type permissionRuleValueFromString = any
export type persistBinaryContent = any
export type persistToolResult = any
export type prefetchAwsCredentialsAndBedRockInfoIfSafe = any
export type prefetchFastModeStatus = any
export type prefetchGcpCredentialsIfSafe = any
export type profileCheckpoint = any
export type promptRequestSchema = any
export type queuePendingMessage = any
export type randomUUID = any
export type readFile = any
export type readImageWithTokenBudget = any
export type readdir = any
export type redownloadUserSettings = any
export type refreshPolicyLimits = any
export type regenerateSessionId = any
export type registerForeground = any
export type registerLeaderSetToolPermissionContext = any
export type registerPermissionCallback = any
export type relative = any
export type removeLastFromHistory = any
export type renderAndRun = any
export type resetAnchor = any
export type resetCostState = any
export type resetTurnHookDuration = any
export type resetTurnToolDuration = any
export type resolve = any
export type roughTokenCountEstimation = any
export type runElicitationHooks = any
export type runElicitationResultHooks = any
export type runForkedAgent = any
export type sameSessionId = any
export type sanitizeToolNameForAnalytics = any
export type saveCurrentSessionCosts = any
export type saveGlobalConfig = any
export type scanMemoryFiles = any
export type selectableUserMessagesFilter = any
export type sendSandboxPermissionRequestViaMailbox = any
export type setAdditionalDirectoriesForAstroMd = any
export type setCostStateForRestore = any
export type setIsRemoteMode = any
export type setLastApiCompletionTimestamp = any
export type setLastClassifierRequests = any
export type setMainLoopModelOverride = any
export type setMainThreadAgentType = any
export type setOriginalCwd = any
export type shouldAllowManagedHooksOnly = any
export type shouldDisableAllHooksIncludingManaged = any
export type sortLogs = any
export type spawnShellTask = any
export type startHookProgressInterval = any
export type stat = any
export type stripTrailingWhitespace = any
export type subscribeTerminalFocus = any
export type substituteUserConfigVariables = any
export type switchSession = any
export type toolMatchesName = any
export type truncate = any
export type truncateMcpContentIfNeeded = any
export type unlink = any
export type unregisterLeaderToolUseConfirmQueue = any
export type unregisterPermissionCallback = any
export type updateAgentProgress = any
export type updateProgressFromMessage = any
export type use = any
export type useAppState = any
export type useAppStateStore = any
export type useCallback = any
export type useContext = any
export type useDeferredValue = any
export type useEffect = any
export type useImperativeHandle = any
export type useLayoutEffect = any
export type useMemo = any
export type usePromptOverlay = any
export type useRef = any
export type useState = any
export type useStdin = any
export type useTerminalFocus = any
export type useTerminalTitle = any
export type useTheme = any
export type waitForPolicyLimitsToLoad = any
export type withDiagnosticsTiming = any
export type withMemoryCorrectionHint = any
export type wrapInSystemReminder = any
export type writeFile = any

export const AGENT_COLORS: any = stub
export const APIConnectionError: any = stub
export const APIConnectionTimeoutError: any = stub
export const APIError: any = stub
export const APIUserAbortError: any = stub
export const ASYNC_AGENT_ALLOWED_TOOLS: any = stub
export const AgentDefinitionsResult: any = stub
export const AssistantMessage: any = stub
export const AsyncHookJSONOutput: any = stub
export const AttachmentMessage: any = stub
export const BetaStopReason: any = stub
export const BetaUsage: any = stub
export const BoundedUUIDSet: any = stub
export const Box: any = stub
export const BridgeFatalError: any = stub
export const BriefIdleStatus: any = stub
export const COMMAND_MESSAGE_TAG: any = stub
export const COMMAND_NAME_TAG: any = stub
export const CUSTOM_AGENT_DISALLOWED_TOOLS: any = stub
export const CollapsedReadSearchGroup: any = stub
export const CollapsibleMessage: any = stub
export const CompactMetadata: any = stub
export const ConfigChangeHookInput: any = stub
export const ContentBlockParam: any = stub
export const ContextCollapseCommitEntry: any = stub
export const ContextCollapseSnapshotEntry: any = stub
export const CustomAgentDefinition: any = stub
export const CwdChangedHookInput: any = stub
export const DEFAULT_MAX_RESULT_SIZE_CHARS: any = stub
export const DirectConnectSessionManager: any = stub
export const ERROR_MESSAGE_INCOMPLETE_RESPONSE: any = stub
export const ERROR_MESSAGE_NOT_ENOUGH_MESSAGES: any = stub
export const ERROR_MESSAGE_USER_ABORT: any = stub
export const ElicitRequestSchema: any = stub
export const ElicitationHookInput: any = stub
export const ElicitationResultHookInput: any = stub
export const ErrorCode: any = stub
export const ExitReason: any = stub
export const FILE_UNCHANGED_STUB: any = stub
export const FORK_DIRECTIVE_PREFIX: any = stub
export const FileChangedHookInput: any = stub
export const GroupedToolUseMessage: any = stub
export const HOOK_EVENTS: any = stub
export const HookCommand: any = stub
export const HookInput: any = stub
export const HookJSONOutput: any = stub
export const HookResultMessage: any = stub
export const IDLE_SPECULATION_STATE: any = stub
export const IN_PROCESS_TEAMMATE_ALLOWED_TOOLS: any = stub
export const ImageBlockParam: any = stub
export const InstructionsLoadedHookInput: any = stub
export const InvalidArgumentError: any = stub
export const JSONRPCMessage: any = stub
export const LOCAL_COMMAND_STDOUT_TAG: any = stub
export const ListPromptsResultSchema: any = stub
export const ListResourcesResultSchema: any = stub
export const ListRootsRequestSchema: any = stub
export const ListToolsResultSchema: any = stub
export const LogOption: any = stub
export const MANUAL_COMPACT_BUFFER_TOKENS: any = stub
export const MAX_TOOL_RESULTS_PER_MESSAGE_CHARS: any = stub
export const MAX_TOOL_RESULT_BYTES: any = stub
export const MCPServerConnection: any = stub
export const MaxFileReadTokenExceededError: any = stub
export const McpError: any = stub
export const McpServerConfig: any = stub
export const Message: any = stub
export const MessageOrigin: any = stub
export const MessageParam: any = stub
export const NormalizedAssistantMessage: any = stub
export const NormalizedMessage: any = stub
export const NormalizedUserMessage: any = stub
export const NotificationHookInput: any = stub
export const PartialCompactDirection: any = stub
export const PermissionDeniedHookInput: any = stub
export const PermissionRequestHookInput: any = stub
export const PermissionUpdate: any = stub
export const PersistedWorktreeSession: any = stub
export const PluginHookMatcher: any = stub
export const PostCompactHookInput: any = stub
export const PostToolUseFailureHookInput: any = stub
export const PostToolUseHookInput: any = stub
export const PreCompactHookInput: any = stub
export const PreToolUseHookInput: any = stub
export const ProgressMessage: any = stub
export const QueuedCommand: any = stub
export const REFERENCE_MARK: any = stub
export const REJECT_MESSAGE: any = stub
export const RedactedThinkingBlock: any = stub
export const RedactedThinkingBlockParam: any = stub
export const RemoteSessionManager: any = stub
export const RenderableMessage: any = stub
export const RequestStartEvent: any = stub
export const SDKCompactBoundaryMessage: any = stub
export const SDKControlResponse: any = stub
export const SDKMessage: any = stub
export const SDKPermissionDenial: any = stub
export const SDKRateLimitInfo: any = stub
export const SDKStatus: any = stub
export const SDKUserMessageReplay: any = stub
export const STATUS_TAG: any = stub
export const SUMMARY_TAG: any = stub
export const SYSTEM_PROMPT_DYNAMIC_BOUNDARY: any = stub
export const ScopedMcpServerConfig: any = stub
export const SerializedMessage: any = stub
export const SessionEndHookInput: any = stub
export const SessionStartHookInput: any = stub
export const SetupHookInput: any = stub
export const SkillHookMatcher: any = stub
export const StopFailureHookInput: any = stub
export const StopHookInfo: any = stub
export const StopHookInput: any = stub
export const StreamEvent: any = stub
export const SubagentStartHookInput: any = stub
export const SubagentStopHookInput: any = stub
export const SyncHookJSONOutput: any = stub
export const SystemAPIErrorMessage: any = stub
export const SystemAgentsKilledMessage: any = stub
export const SystemApiMetricsMessage: any = stub
export const SystemAwaySummaryMessage: any = stub
export const SystemBridgeStatusMessage: any = stub
export const SystemCompactBoundaryMessage: any = stub
export const SystemFileSnapshotMessage: any = stub
export const SystemInformationalMessage: any = stub
export const SystemLocalCommandMessage: any = stub
export const SystemMemorySavedMessage: any = stub
export const SystemMessage: any = stub
export const SystemMessageLevel: any = stub
export const SystemMicrocompactBoundaryMessage: any = stub
export const SystemPermissionRetryMessage: any = stub
export const SystemScheduledTaskFireMessage: any = stub
export const SystemStopHookSummaryMessage: any = stub
export const SystemThinkingMessage: any = stub
export const SystemTurnDurationMessage: any = stub
export const TASK_ID_TAG: any = stub
export const TASK_NOTIFICATION_TAG: any = stub
export const TOOL_SEARCH_TOOL_NAME: any = stub
export const TOOL_USE_ID_TAG: any = stub
export const Task: any = stub
export const TaskCompletedHookInput: any = stub
export const TaskCreatedHookInput: any = stub
export const TeammateIdentity: any = stub
export const TeammateIdleHookInput: any = stub
export const TelemetrySafeError_I_VERIFIED_THIS_IS_NOT_CODE_OR_FILEPATHS: any = stub
export const TeleportError: any = stub
export const Text: any = stub
export const TextBlockParam: any = stub
export const ThinkingBlock: any = stub
export const ThinkingBlockParam: any = stub
export const TombstoneMessage: any = stub
export const Tool: any = stub
export const ToolCallProgress: any = stub
export const ToolPermissionContext: any = stub
export const ToolResult: any = stub
export const ToolResultBlockParam: any = stub
export const ToolUseBlock: any = stub
export const ToolUseBlockParam: any = stub
export const ToolUseContext: any = stub
export const ToolUseSummaryMessage: any = stub
export const Tools: any = stub
export const UserMessage: any = stub
export const UserPromptSubmitHookInput: any = stub
export const ValidationResult: any = stub
export const WORKTREE_BRANCH_TAG: any = stub
export const WORKTREE_PATH_TAG: any = stub
export const addToTurnHookDuration: any = stub
export const appendMessageToLocalAgent: any = stub
export const applyPermissionUpdates: any = stub
export const asAgentId: any = stub
export const asSessionId: any = stub
export const buildCCRv2SdkUrl: any = stub
export const buildSdkUrl: any = stub
export const c: any = stub
export const compactConversation: any = stub
export const consumePostCompaction: any = stub
export const copyFile: any = stub
export const countTokensViaHaikuFallback: any = stub
export const createActivityDescriptionResolver: any = stub
export const createAgentsKilledMessage: any = stub
export const createApiMetricsMessage: any = stub
export const createAssistantMessage: any = stub
export const createCacheSafeParams: any = stub
export const createCommandInputMessage: any = stub
export const createHash: any = stub
export const createMemorySavedMessage: any = stub
export const createProgressTracker: any = stub
export const createSystemMessage: any = stub
export const createToolStub: any = stub
export const createTurnDurationMessage: any = stub
export const createUserMessage: any = stub
export const createV1ReplTransport: any = stub
export const createV2ReplTransport: any = stub
export const detectGitOperation: any = stub
export const dirname: any = stub
export const downloadSessionFiles: any = stub
export const emitHookResponse: any = stub
export const endHookSpan: any = stub
export const enhanceSystemPromptWithEnvDetails: any = stub
export const enqueueAgentNotification: any = stub
export const exitTeammateView: any = stub
export const exitWithMessage: any = stub
export const expandPastedTextRefs: any = stub
export const extractHttpStatus: any = stub
export const extractSkillName: any = stub
export const extractTitleText: any = stub
export const extractToolInputForTelemetry: any = stub
export const failAgentTask: any = stub
export const fetchLatestEvents: any = stub
export const fetchOlderEvents: any = stub
export const fetchToolsForClient: any = stub
export const fileHistoryCanRestore: any = stub
export const fileHistoryEnabled: any = stub
export const filterToolProgressMessages: any = stub
export const findCommand: any = stub
export const findToolByName: any = stub
export const formatDescriptionWithSource: any = stub
export const formatPastedTextRef: any = stub
export const fstatSync: any = stub
export const generateSandboxRequestId: any = stub
export const getActiveAgentsFromList: any = stub
export const getAgentDefinitionsWithOverrides: any = stub
export const getAgentTranscriptPath: any = stub
export const getBudgetContinuationCount: any = stub
export const getCLISyspromptPrefix: any = stub
export const getAstroAIOAuthTokens: any = stub
export const getCodeEditToolDecisionCounter: any = stub
export const getCommand: any = stub
export const getCommandName: any = stub
export const getCommands: any = stub
export const getConditionalRulesForCwdLevelDirectory: any = stub
export const getContentText: any = stub
export const getCurrentTurnTokenBudget: any = stub
export const getEffectiveContextWindowSize: any = stub
export const getFeatureValue_CACHED_MAY_BE_STALE: any = stub
export const getFileExtensionForAnalytics: any = stub
export const getFileExtensionsFromBashCommand: any = stub
export const getFormatDescription: any = stub
export const getGlobalConfig: any = stub
export const getInitialAdvisorSetting: any = stub
export const getIsNonInteractiveSession: any = stub
export const getKairosActive: any = stub
export const getLargeOutputInstructions: any = stub
export const getLastApiCompletionTimestamp: any = stub
export const getLastAssistantMessage: any = stub
export const getLastClassifierRequests: any = stub
export const getLastInteractionTime: any = stub
export const getLegacyToolNames: any = stub
export const getMainThreadAgentType: any = stub
export const getManagedAndUserConditionalRules: any = stub
export const getMemoryFiles: any = stub
export const getMemoryFilesForNestedDirectory: any = stub
export const getMessagesAfterCompactBoundary: any = stub
export const getOriginalCwd: any = stub
export const getPastedTextRefNumLines: any = stub
export const getPdfInvalidErrorMessage: any = stub
export const getPdfPasswordProtectedErrorMessage: any = stub
export const getPdfTooLargeErrorMessage: any = stub
export const getPlanSlugCache: any = stub
export const getProgressUpdate: any = stub
export const getProjectRoot: any = stub
export const getPromptId: any = stub
export const getRegisteredHooks: any = stub
export const getRemoteControlAtStartup: any = stub
export const getRenderContext: any = stub
export const getRequestTooLargeErrorMessage: any = stub
export const getSdkBetas: any = stub
export const getSessionId: any = stub
export const getSessionProjectDir: any = stub
export const getSettingsForSource: any = stub
export const getSkillToolCommands: any = stub
export const getSkillToolInfo: any = stub
export const getStatsStore: any = stub
export const getTaskListId: any = stub
export const getTeleportedSessionInfo: any = stub
export const getTokenCountFromTracker: any = stub
export const getTotalAPIDuration: any = stub
export const getTotalCost: any = stub
export const getTotalDuration: any = stub
export const getTotalInputTokens: any = stub
export const getTotalLinesAdded: any = stub
export const getTotalLinesRemoved: any = stub
export const getTurnClassifierCount: any = stub
export const getTurnClassifierDurationMs: any = stub
export const getTurnHookCount: any = stub
export const getTurnHookDurationMs: any = stub
export const getTurnOutputTokens: any = stub
export const getTurnToolCount: any = stub
export const getTurnToolDurationMs: any = stub
export const getWebSocketProxyAgent: any = stub
export const getWebSocketProxyUrl: any = stub
export const handleKeyEvent: any = stub
export const handleMessageFromStream: any = stub
export const handleOAuth401Error: any = stub
export const handleServerControlRequest: any = stub
export const handleTranscriptSelect: any = stub
export const hasCommand: any = stub
export const initializeGrowthBook: any = stub
export const injectUserMessageToTeammate: any = stub
export const invalidateSessionEnvCache: any = stub
export const isAbsolute: any = stub
export const isAdvisorEnabled: any = stub
export const isAsyncHookJSONOutput: any = stub
export const isAutoCompactEnabled: any = stub
export const isAutoMemPath: any = stub
export const isAutoMemoryEnabled: any = stub
export const isAutoUpdaterDisabled: any = stub
export const isBetaTracingEnabled: any = stub
export const isBridgeSafeCommand: any = stub
export const isBuiltInAgent: any = stub
export const isAstroAISubscriber: any = stub
export const isCodeEditingTool: any = stub
export const isCompactBoundaryMessage: any = stub
export const isConnectorTextBlock: any = stub
export const isCustomAgent: any = stub
export const isDeferredTool: any = stub
export const isEligibleBridgeMessage: any = stub
export const isExpiredErrorType: any = stub
export const isFastModeEnabled: any = stub
export const isFirstPartyAnthropicBaseUrl: any = stub
export const isLocalAgentTask: any = stub
export const isSessionEndMessage: any = stub
export const isSessionPersistenceDisabled: any = stub
export const isSuppressible403: any = stub
export const isSyncHookJSONOutput: any = stub
export const isTerminalTaskStatus: any = stub
export const isTodoV2Enabled: any = stub
export const isToolDetailsLoggingEnabled: any = stub
export const isValidAdvisorModel: any = stub
export const join: any = stub
export const killAsyncAgent: any = stub
export const launchAssistantSessionChooser: any = stub
export const launchInvalidSettingsDialog: any = stub
export const launchResumeChooser: any = stub
export const launchSnapshotUpdateDialog: any = stub
export const launchTeleportRepoMismatchDialog: any = stub
export const listTasks: any = stub
export const loadPolicyLimits: any = stub
export const logBridgeSkip: any = stub
export const logEvent: any = stub
export const makeResultMessage: any = stub
export const markFirstTeleportMessageLogged: any = stub
export const markTaskNotified: any = stub
export const mcpContentNeedsTruncation: any = stub
export const mcpInfoFromString: any = stub
export const mcpToolDetailsForAnalytics: any = stub
export const mergeFileStateCaches: any = stub
export const mergeHookInstructions: any = stub
export const mkdir: any = stub
export const open: any = stub
export const openSync: any = stub
export const parse: any = stub
export const parseAgentsFromJson: any = stub
export const permissionRuleValueFromString: any = stub
export const persistBinaryContent: any = stub
export const persistToolResult: any = stub
export const prefetchAwsCredentialsAndBedRockInfoIfSafe: any = stub
export const prefetchFastModeStatus: any = stub
export const prefetchGcpCredentialsIfSafe: any = stub
export const profileCheckpoint: any = stub
export const promptRequestSchema: any = stub
export const queuePendingMessage: any = stub
export const randomUUID: any = stub
export const readFile: any = stub
export const readImageWithTokenBudget: any = stub
export const readdir: any = stub
export const redownloadUserSettings: any = stub
export const refreshPolicyLimits: any = stub
export const regenerateSessionId: any = stub
export const registerForeground: any = stub
export const registerLeaderSetToolPermissionContext: any = stub
export const registerPermissionCallback: any = stub
export const relative: any = stub
export const removeLastFromHistory: any = stub
export const renderAndRun: any = stub
export const resetAnchor: any = stub
export const resetCostState: any = stub
export const resetTurnHookDuration: any = stub
export const resetTurnToolDuration: any = stub
export const resolve: any = stub
export const roughTokenCountEstimation: any = stub
export const runElicitationHooks: any = stub
export const runElicitationResultHooks: any = stub
export const runForkedAgent: any = stub
export const sameSessionId: any = stub
export const sanitizeToolNameForAnalytics: any = stub
export const saveCurrentSessionCosts: any = stub
export const saveGlobalConfig: any = stub
export const scanMemoryFiles: any = stub
export const selectableUserMessagesFilter: any = stub
export const sendSandboxPermissionRequestViaMailbox: any = stub
export const setAdditionalDirectoriesForAstroMd: any = stub
export const setCostStateForRestore: any = stub
export const setIsRemoteMode: any = stub
export const setLastApiCompletionTimestamp: any = stub
export const setLastClassifierRequests: any = stub
export const setMainLoopModelOverride: any = stub
export const setMainThreadAgentType: any = stub
export const setOriginalCwd: any = stub
export const shouldAllowManagedHooksOnly: any = stub
export const shouldDisableAllHooksIncludingManaged: any = stub
export const sortLogs: any = stub
export const spawnShellTask: any = stub
export const startHookProgressInterval: any = stub
export const stat: any = stub
export const stripTrailingWhitespace: any = stub
export const subscribeTerminalFocus: any = stub
export const substituteUserConfigVariables: any = stub
export const switchSession: any = stub
export const toolMatchesName: any = stub
export const truncate: any = stub
export const truncateMcpContentIfNeeded: any = stub
export const unlink: any = stub
export const unregisterLeaderToolUseConfirmQueue: any = stub
export const unregisterPermissionCallback: any = stub
export const updateAgentProgress: any = stub
export const updateProgressFromMessage: any = stub
export const use: any = stub
export const useAppState: any = stub
export const useAppStateStore: any = stub
export const useCallback: any = stub
export const useContext: any = stub
export const useDeferredValue: any = stub
export const useEffect: any = stub
export const useImperativeHandle: any = stub
export const useLayoutEffect: any = stub
export const useMemo: any = stub
export const usePromptOverlay: any = stub
export const useRef: any = stub
export const useState: any = stub
export const useStdin: any = stub
export const useTerminalFocus: any = stub
export const useTerminalTitle: any = stub
export const useTheme: any = stub
export const waitForPolicyLimitsToLoad: any = stub
export const withDiagnosticsTiming: any = stub
export const withMemoryCorrectionHint: any = stub
export const wrapInSystemReminder: any = stub
export const writeFile: any = stub

export default stub
