/*
 * AUTO-GENERATED COMPATIBILITY STUB.
 *
 * The recovered source tree imports this module, but the original file is
 * absent from this checkout. This stub only exists so local tooling can
 * resolve modules; it is not a replacement for the original implementation.
 */

type StubCallable = ((...args: unknown[]) => unknown) & Record<PropertyKey, unknown>

const createStub = (label: string): StubCallable => {
  const target = function compatibilityStub() {
    throw new Error(`Missing original implementation for src/utils/udsMessaging.ts (${label})`)
  } as StubCallable
  return new Proxy(target, {
    get(current, prop) {
      if (prop === 'then') return undefined
      if (prop === Symbol.toStringTag) return 'CompatibilityStub'
      if (prop in current) return current[prop]
      return createStub(`${label}.${String(prop)}`)
    },
    apply() {
      throw new Error(`Missing original implementation for src/utils/udsMessaging.ts (${label})`)
    },
    construct() {
      throw new Error(`Missing original implementation for src/utils/udsMessaging.ts (${label})`)
    },
  })
}

const stub = createStub("src/utils/udsMessaging.ts")

export type AnalyticsMetadata_I_VERIFIED_THIS_IS_NOT_CODE_OR_FILEPATHS = any
export type Attachment = any
export type ChannelEntry = any
export type AstroAILimits = any
export type EFFORT_LEVELS = any
export type ElicitationCompleteNotificationSchema = any
export type McpSdkServerConfig = any
export type McpServerConfigForProcessTransport = any
export type McpServerStatus = any
export type ModelInfo = any
export type PermissionResult = any
export type PromptVariant = any
export type READ_FILE_STATE_CACHE_SIZE = any
export type RequiresActionDetails = any
export type RewindFilesResult = any
export type SDKControlInitializeRequest = any
export type SDKControlInitializeResponse = any
export type SDKControlMcpSetServersResponse = any
export type SDKControlReloadPluginsResponse = any
export type SDKControlRequest = any
export type SDKControlResponse = any
export type SDKMessage = any
export type SDKUserMessage = any
export type SDKUserMessageReplay = any
export type ScopedMcpServerConfig = any
export type SessionExternalMetadata = any
export type Tool = any
export type TurnInterruptionState = any
export type User = any
export type abortController = any
export type action = any
export type agent = any
export type agentSetting = any
export type agents = any
export type allAgents = any
export type annotations = any
export type appendSystemPrompt = any
export type applyMcpServerChanges = any
export type areMcpConfigsEqual = any
export type args = any
export type assembledTools = any
export type attribution = any
export type bg_tasks = any
export type bridge = any
export type cacheSafeParams = any
export type canUseTool = any
export type capabilities = any
export type checkGroveForNonInteractive = any
export type clearServerCache = any
export type clients = any
export type command = any
export type commands = any
export type config = any
export type configs = any
export type connectToServer = any
export type content = any
export type currentAppState = any
export type customSystemPrompt = any
export type cwd = any
export type dequeueAllMatching = any
export type description = any
export type destructive = any
export type displayName = any
export type doesMessageExistInSession = any
export type duration_api_ms = any
export type duration_ms = any
export type dynamicMcpState = any
export type elicitSignal = any
export type elicitationId = any
export type elicitation_id = any
export type emittedAt = any
export type enqueue = any
export type error = any
export type errors = any
export type exit_code = any
export type failed = any
export type fallbackModel = any
export type fetchToolsForClient = any
export type fileHistoryCanRestore = any
export type fileHistoryEnabled = any
export type fileHistoryGetDiffStats = any
export type files = any
export type filterToolsByServer = any
export type filteredTools = any
export type findChannelEntry = any
export type findUnresolvedToolUse = any
export type forkSession = any
export type formatDescriptionWithSource = any
export type gateChannelServer = any
export type generationRequestId = any
export type getAllOutputStyles = any
export type getAllowedChannels = any
export type getAppState = any
export type getAutoModeUnavailableNotification = any
export type getAutoModeUnavailableReason = any
export type getCommandName = any
export type getCommandsByMaxPriority = any
export type getFastModeState = any
export type getFlagSettingsInline = any
export type getInitJsonSchema = any
export type getIsRemoteMode = any
export type getMainLoopModel = any
export type getMainThreadAgentType = any
export type getMcpConfigByName = any
export type getReadFileCache = any
export type getSettingsWithSources = any
export type getUdsMessagingSocketPath = any
export type gracefulShutdownSync = any
export type handleElicitation = any
export type hasActiveInProcessTeammates = any
export type hasCommandsInQueue = any
export type hasWorkingInProcessTeammates = any
export type headers = any
export type headlessProfilerCheckpoint = any
export type hook_event = any
export type hook_id = any
export type hook_name = any
export type hydrateFromCCRv2InternalEvents = any
export type id = any
export type includePartialMessages = any
export type inflightPromise = any
export type initialMessages = any
export type inputText = any
export type internal_events_pending = any
export type isAuthenticating = any
export type isBuiltInAgent = any
export type isBypassPermissionsModeDisabled = any
export type isChannelsEnabled = any
export type isEnvDefinedFalsy = any
export type isEnvTruthy = any
export type isFastModeEnabled = any
export type isFastModeSupportedByModel = any
export type isMcpServerDisabled = any
export type isMeta = any
export type isReplay = any
export type isSessionPersistenceDisabled = any
export type isShutdownApproved = any
export type isShuttingDown = any
export type is_error = any
export type jsonSchema = any
export type lastEmitted = any
export type logError = any
export type logHeadlessProfilerTurn = any
export type logQueryProfileReport = any
export type logSuggestionOutcome = any
export type logSuggestionSuppressed = any
export type markMessagesAsRead = any
export type maxBudgetUsd = any
export type maxTurns = any
export type mcp = any
export type mcpClients = any
export type mcp_server_name = any
export type merge = any
export type mergeFileStateCaches = any
export type message = any
export type mode = any
export type modelDisplayString = any
export type modelSupportsMaxEffort = any
export type modelUsage = any
export type mutableMessages = any
export type name = any
export type next = any
export type notification = any
export type notificationType = any
export type notifySessionMetadataChanged = any
export type notifySessionStateChanged = any
export type num_turns = any
export type oauth = any
export type onPermissionPrompt = any
export type openWorld = any
export type options = any
export type orphanedPermission = any
export type outcome = any
export type output = any
export type outputFormat = any
export type output_file = any
export type params = any
export type parent_tool_use_id = any
export type parseAgentsFromJson = any
export type parseUserSpecifiedModel = any
export type peek = any
export type pendingLastEmittedEntry = any
export type pendingSuggestion = any
export type permissionMode = any
export type permissionPromptCount = any
export type permissionPromptToolResultToPermissionDecision = any
export type permission_denials = any
export type priority = any
export type processSetupHooks = any
export type processed_at = any
export type prompt = any
export type promptId = any
export type promptUuid = any
export type rate_limit_info = any
export type rawResult = any
export type reconnectMcpServerImpl = any
export type recordAttributionSnapshot = any
export type redownloadUserSettings = any
export type registerProcessOutputErrorHandlers = any
export type removed = any
export type replayUserMessages = any
export type requestedSchema = any
export type resetSessionFilePointer = any
export type resolveAppliedEffort = any
export type resolvedModel = any
export type restoreSessionMetadata = any
export type restoreSessionStateFromLog = any
export type restoredWorkerState = any
export type result = any
export type resume = any
export type resumeSessionAt = any
export type revokeServerTokens = any
export type rewind = any
export type runElicitationResultHooks = any
export type run_phase = any
export type saveAgentSetting = any
export type saveAiGeneratedTitle = any
export type saveMode = any
export type scope = any
export type sdkClients = any
export type sdkMcpConfigs = any
export type sdkServersChanged = any
export type serverInfo = any
export type sessionStartHooksPromise = any
export type session_id = any
export type setAllowedChannels = any
export type setAppState = any
export type setFlagSettingsInline = any
export type setInitJsonSchema = any
export type setMainLoopModelOverride = any
export type setMainThreadAgentType = any
export type setMcpServerEnabled = any
export type setPermissionModeChangedListener = any
export type setReadFileCache = any
export type setSDKStatus = any
export type setSdkAgentProgressSummariesEnabled = any
export type status = any
export type stderr = any
export type stdout = any
export type stop_reason = any
export type structuredIO = any
export type subscribeToCommandQueue = any
export type subtype = any
export type suggestion = any
export type summary = any
export type supportedEffortLevels = any
export type switchSession = any
export type takeInitialUserMessage = any
export type taskBudget = any
export type task_id = any
export type teamContext = any
export type teammateId = any
export type teammateToRemove = any
export type teammates = any
export type teleport = any
export type text = any
export type thinkingConfig = any
export type timestamp = any
export type toSDKRateLimitInfo = any
export type tool_use_id = any
export type tool_uses = any
export type tools = any
export type total_cost_usd = any
export type transitionPermissionMode = any
export type turnInterruptionState = any
export type url = any
export type usage = any
export type userSpecifiedModel = any
export type uuid = any
export type value = any
export type verbose = any
export type waitForTeammatesToBecomeIdle = any
export type withDiagnosticsTiming = any
export type worker_status = any
export type wrapChannelMessage = any

export const AnalyticsMetadata_I_VERIFIED_THIS_IS_NOT_CODE_OR_FILEPATHS: any = stub
export const Attachment: any = stub
export const ChannelEntry: any = stub
export const AstroAILimits: any = stub
export const EFFORT_LEVELS: any = stub
export const ElicitationCompleteNotificationSchema: any = stub
export const McpSdkServerConfig: any = stub
export const McpServerConfigForProcessTransport: any = stub
export const McpServerStatus: any = stub
export const ModelInfo: any = stub
export const PermissionResult: any = stub
export const PromptVariant: any = stub
export const READ_FILE_STATE_CACHE_SIZE: any = stub
export const RequiresActionDetails: any = stub
export const RewindFilesResult: any = stub
export const SDKControlInitializeRequest: any = stub
export const SDKControlInitializeResponse: any = stub
export const SDKControlMcpSetServersResponse: any = stub
export const SDKControlReloadPluginsResponse: any = stub
export const SDKControlRequest: any = stub
export const SDKControlResponse: any = stub
export const SDKMessage: any = stub
export const SDKUserMessage: any = stub
export const SDKUserMessageReplay: any = stub
export const ScopedMcpServerConfig: any = stub
export const SessionExternalMetadata: any = stub
export const Tool: any = stub
export const TurnInterruptionState: any = stub
export const User: any = stub
export const abortController: any = stub
export const action: any = stub
export const agent: any = stub
export const agentSetting: any = stub
export const agents: any = stub
export const allAgents: any = stub
export const annotations: any = stub
export const appendSystemPrompt: any = stub
export const applyMcpServerChanges: any = stub
export const areMcpConfigsEqual: any = stub
export const args: any = stub
export const assembledTools: any = stub
export const attribution: any = stub
export const bg_tasks: any = stub
export const bridge: any = stub
export const cacheSafeParams: any = stub
export const canUseTool: any = stub
export const capabilities: any = stub
export const checkGroveForNonInteractive: any = stub
export const clearServerCache: any = stub
export const clients: any = stub
export const command: any = stub
export const commands: any = stub
export const config: any = stub
export const configs: any = stub
export const connectToServer: any = stub
export const content: any = stub
export const currentAppState: any = stub
export const customSystemPrompt: any = stub
export const cwd: any = stub
export const dequeueAllMatching: any = stub
export const description: any = stub
export const destructive: any = stub
export const displayName: any = stub
export const doesMessageExistInSession: any = stub
export const duration_api_ms: any = stub
export const duration_ms: any = stub
export const dynamicMcpState: any = stub
export const elicitSignal: any = stub
export const elicitationId: any = stub
export const elicitation_id: any = stub
export const emittedAt: any = stub
export const enqueue: any = stub
export const error: any = stub
export const errors: any = stub
export const exit_code: any = stub
export const failed: any = stub
export const fallbackModel: any = stub
export const fetchToolsForClient: any = stub
export const fileHistoryCanRestore: any = stub
export const fileHistoryEnabled: any = stub
export const fileHistoryGetDiffStats: any = stub
export const files: any = stub
export const filterToolsByServer: any = stub
export const filteredTools: any = stub
export const findChannelEntry: any = stub
export const findUnresolvedToolUse: any = stub
export const forkSession: any = stub
export const formatDescriptionWithSource: any = stub
export const gateChannelServer: any = stub
export const generationRequestId: any = stub
export const getAllOutputStyles: any = stub
export const getAllowedChannels: any = stub
export const getAppState: any = stub
export const getAutoModeUnavailableNotification: any = stub
export const getAutoModeUnavailableReason: any = stub
export const getCommandName: any = stub
export const getCommandsByMaxPriority: any = stub
export const getFastModeState: any = stub
export const getFlagSettingsInline: any = stub
export const getInitJsonSchema: any = stub
export const getIsRemoteMode: any = stub
export const getMainLoopModel: any = stub
export const getMainThreadAgentType: any = stub
export const getMcpConfigByName: any = stub
export const getReadFileCache: any = stub
export const getSettingsWithSources: any = stub
export const getUdsMessagingSocketPath: any = stub
export const gracefulShutdownSync: any = stub
export const handleElicitation: any = stub
export const hasActiveInProcessTeammates: any = stub
export const hasCommandsInQueue: any = stub
export const hasWorkingInProcessTeammates: any = stub
export const headers: any = stub
export const headlessProfilerCheckpoint: any = stub
export const hook_event: any = stub
export const hook_id: any = stub
export const hook_name: any = stub
export const hydrateFromCCRv2InternalEvents: any = stub
export const id: any = stub
export const includePartialMessages: any = stub
export const inflightPromise: any = stub
export const initialMessages: any = stub
export const inputText: any = stub
export const internal_events_pending: any = stub
export const isAuthenticating: any = stub
export const isBuiltInAgent: any = stub
export const isBypassPermissionsModeDisabled: any = stub
export const isChannelsEnabled: any = stub
export const isEnvDefinedFalsy: any = stub
export const isEnvTruthy: any = stub
export const isFastModeEnabled: any = stub
export const isFastModeSupportedByModel: any = stub
export const isMcpServerDisabled: any = stub
export const isMeta: any = stub
export const isReplay: any = stub
export const isSessionPersistenceDisabled: any = stub
export const isShutdownApproved: any = stub
export const isShuttingDown: any = stub
export const is_error: any = stub
export const jsonSchema: any = stub
export const lastEmitted: any = stub
export const logError: any = stub
export const logHeadlessProfilerTurn: any = stub
export const logQueryProfileReport: any = stub
export const logSuggestionOutcome: any = stub
export const logSuggestionSuppressed: any = stub
export const markMessagesAsRead: any = stub
export const maxBudgetUsd: any = stub
export const maxTurns: any = stub
export const mcp: any = stub
export const mcpClients: any = stub
export const mcp_server_name: any = stub
export const merge: any = stub
export const mergeFileStateCaches: any = stub
export const message: any = stub
export const mode: any = stub
export const modelDisplayString: any = stub
export const modelSupportsMaxEffort: any = stub
export const modelUsage: any = stub
export const mutableMessages: any = stub
export const name: any = stub
export const next: any = stub
export const notification: any = stub
export const notificationType: any = stub
export const notifySessionMetadataChanged: any = stub
export const notifySessionStateChanged: any = stub
export const num_turns: any = stub
export const oauth: any = stub
export const onPermissionPrompt: any = stub
export const openWorld: any = stub
export const options: any = stub
export const orphanedPermission: any = stub
export const outcome: any = stub
export const output: any = stub
export const outputFormat: any = stub
export const output_file: any = stub
export const params: any = stub
export const parent_tool_use_id: any = stub
export const parseAgentsFromJson: any = stub
export const parseUserSpecifiedModel: any = stub
export const peek: any = stub
export const pendingLastEmittedEntry: any = stub
export const pendingSuggestion: any = stub
export const permissionMode: any = stub
export const permissionPromptCount: any = stub
export const permissionPromptToolResultToPermissionDecision: any = stub
export const permission_denials: any = stub
export const priority: any = stub
export const processSetupHooks: any = stub
export const processed_at: any = stub
export const prompt: any = stub
export const promptId: any = stub
export const promptUuid: any = stub
export const rate_limit_info: any = stub
export const rawResult: any = stub
export const reconnectMcpServerImpl: any = stub
export const recordAttributionSnapshot: any = stub
export const redownloadUserSettings: any = stub
export const registerProcessOutputErrorHandlers: any = stub
export const removed: any = stub
export const replayUserMessages: any = stub
export const requestedSchema: any = stub
export const resetSessionFilePointer: any = stub
export const resolveAppliedEffort: any = stub
export const resolvedModel: any = stub
export const restoreSessionMetadata: any = stub
export const restoreSessionStateFromLog: any = stub
export const restoredWorkerState: any = stub
export const result: any = stub
export const resume: any = stub
export const resumeSessionAt: any = stub
export const revokeServerTokens: any = stub
export const rewind: any = stub
export const runElicitationResultHooks: any = stub
export const run_phase: any = stub
export const saveAgentSetting: any = stub
export const saveAiGeneratedTitle: any = stub
export const saveMode: any = stub
export const scope: any = stub
export const sdkClients: any = stub
export const sdkMcpConfigs: any = stub
export const sdkServersChanged: any = stub
export const serverInfo: any = stub
export const sessionStartHooksPromise: any = stub
export const session_id: any = stub
export const setAllowedChannels: any = stub
export const setAppState: any = stub
export const setFlagSettingsInline: any = stub
export const setInitJsonSchema: any = stub
export const setMainLoopModelOverride: any = stub
export const setMainThreadAgentType: any = stub
export const setMcpServerEnabled: any = stub
export const setPermissionModeChangedListener: any = stub
export const setReadFileCache: any = stub
export const setSDKStatus: any = stub
export const setSdkAgentProgressSummariesEnabled: any = stub
export const status: any = stub
export const stderr: any = stub
export const stdout: any = stub
export const stop_reason: any = stub
export const structuredIO: any = stub
export const subscribeToCommandQueue: any = stub
export const subtype: any = stub
export const suggestion: any = stub
export const summary: any = stub
export const supportedEffortLevels: any = stub
export const switchSession: any = stub
export const takeInitialUserMessage: any = stub
export const taskBudget: any = stub
export const task_id: any = stub
export const teamContext: any = stub
export const teammateId: any = stub
export const teammateToRemove: any = stub
export const teammates: any = stub
export const teleport: any = stub
export const text: any = stub
export const thinkingConfig: any = stub
export const timestamp: any = stub
export const toSDKRateLimitInfo: any = stub
export const tool_use_id: any = stub
export const tool_uses: any = stub
export const tools: any = stub
export const total_cost_usd: any = stub
export const transitionPermissionMode: any = stub
export const turnInterruptionState: any = stub
export const url: any = stub
export const usage: any = stub
export const userSpecifiedModel: any = stub
export const uuid: any = stub
export const value: any = stub
export const verbose: any = stub
export const waitForTeammatesToBecomeIdle: any = stub
export const withDiagnosticsTiming: any = stub
export const worker_status: any = stub
export const wrapChannelMessage: any = stub

export default stub
